### ISSUE TITLE
Research: Can we make coverage faster?

### ISSUE THREAD

**Issue by franzwilding** [unite-cms/unite-cms#140]

**Comment by stefan-kamsker** [comment]
My outcome:

**xdebug**
is really slow, hard to speed that up with simple settings
Did a profiling to find the slowest tests, so maybe refacoring those would be a big improvment
[phpunit.txt](https://github.com/unite-cms/unite-cms/files/2145162/phpunit.txt)
https://github.com/johnkary/phpunit-speedtrap

**Switch to phpdbg** 
ist really fast compared to xdebug, but there are problems with some limits (even on my local machine)
-open file limit (can be set with ulimit -n xy)
-memory exhausts on some tests
is PHP built in (if compiled)
fe. phpdbg -qrr phpunit-7.1.5.phar --coverage-html /var/www/report
https://docs.travis-ci.com/user/speeding-up-the-build/

**Run tests in parallell**
we can try to run tests in parallell
https://github.com/paratestphp/paratest
or check what symfony does https://github.com/symfony/symfony/blob/master/.travis.yml (seems complicated :))
