### ISSUE TITLE
Feedback for invitation if already registered

### ISSUE THREAD

**Issue by stefan-kamsker** [unite-cms/unite-cms#158]
if an already registered user is invited to a organization per mail, he/she will be redirected to login after clicking the link in the mail with no feedback.

Should be some message: (pseudo)
"You are already registered, please login in to accept the invitaition"

this feels confusing to me

**Comment by franzwilding** [comment]
I would add this to the 0.5.5 milestone because you are right. This is very confusing. I think the message should only be something like "Please login in see the invitation".
