### ISSUE TITLE
Autologin after registration is not working

### ISSUE THREAD

**Issue by franzwilding** [unite-cms/unite-cms#172]
Maybe this is related to #169 and can be fixed together.

**Comment by stefan-kamsker** [comment]
i can't reproduce this anymore (with 3 different browsers and users), maybe it was solved somehow

please recheck and provide further details (eg. provide exact steps) if it is still a problem

**Comment by franzwilding** [comment]
After updating to version 0.5.6, I also cannot reproduce it. Maybe a this fixed it or I had a local cookie problem. Thank you for looking into it!
