### ISSUE TITLE
Fix Deprecation warnings

### ISSUE THREAD

**Issue by stefan-kamsker** [unite-cms/unite-cms#173]
![bildschirmfoto 2018-07-06 um 15 27 50](https://user-images.githubusercontent.com/34944934/42381420-478a2b34-8131-11e8-9b66-aa72ca55b8ea.png)

**Comment by franzwilding** [comment]
There is one deprecation warning left, that should be fixed with the next Symfony release @see https://github.com/symfony/symfony/pull/27609
