### ISSUE TITLE
field data processors or tokens

### ISSUE THREAD

**Issue by stefan-kamsker** [unite-cms/unite-cms#218]
We should discuss if we should provide something like field data processors fe. field data manipulation on content CREATE / UPDATE events

this **could** also partially be done on the frontend side

**Use cases:**
automatic slug generations of eg. page titles [AZ-a-z0-9-] for routes
automatic meta description generation (strip tags, shorten text)
prefill from other fields

should be configurable and there should be a possibility to override it 

maybe tokens are a solution fe. [body:summary]

**Comment by franzwilding** [comment]
This could be a new field type "auto" or something, that allows automatic generation from another field or custom override

**Comment by Clonk-HTML5** [comment]
For the frontend routing this will be an must have.
Thanks
