### ISSUE TITLE
Provide Common AWS examples

### ISSUE THREAD

**Issue by stefan-kamsker** [unite-cms/unite-cms#219]
Provide some common examples how to use AWS S3 storage and Thumbnailing Services

https://github.com/awslabs/serverless-image-resizing
https://aws.amazon.com/de/blogs/compute/resize-images-on-the-fly-with-amazon-s3-aws-lambda-and-amazon-api-gateway/

**Comment by stefan-kamsker** [comment]
@franzwilding 

What should be exactly in this tutorial? (Unfortunately due to  #321 not so clear for me anymore)

- register a AWS S3 bucket and configure it with image type
- write and show a small example frontend app which knows the external image resizing service (fe. Cloudimage, Thumbor), pulls the image(s) over graphQL api, builds the different resizing urls and fe. feeds an picture/srcset element

**Comment by franzwilding** [comment]
With this tutorial, devs should be able to set up unite cms with an amazon s3 or minion s3 storage and know how to consume the images in a frontend app and how we handle resizing

**Comment by stefan-kamsker** [comment]
https://medium.com/unite-cms/how-to-setup-s3-storage-along-with-unite-cms-and-do-image-resizing-using-external-services-6cde2cc6a86e

documention is updated
