### ISSUE TITLE
UI improvement - Jump to first error on domain edit

### ISSUE THREAD

**Issue by stefan-kamsker** [unite-cms/unite-cms#230]
If the domain config is getting really long, it would help to jump to the first error, if possible.

**Ideas:**
use background color red for errors

**Ultra Cool:**
a possibility to navigate through all erros (arrow up, arrow down (fe. jump to the next error) )

![error](https://user-images.githubusercontent.com/34944934/45157629-fd495680-b1e1-11e8-9620-8f6d192ae5da.png)

**Comment by franzwilding** [comment]
Maybe we can even show the errors in the editor? I think there is an annotation API for ace (https://ace.c9.io/#nav=api&api=edit_session) we can use.

**Comment by franzwilding** [comment]
No longer needed in 0.10
