### ISSUE TITLE
Provide tree sort functionality for content

### ISSUE THREAD

**Issue by stefan-kamsker** [unite-cms/unite-cms#231]
similar to taxonomies

fe. for tagging or categories

- Taggroup 1
    - Tag1
    - Tag2
    - Tag3
- Taggroup 2
    - Tag 1
        - Subtag 1
    - Tag 2

----------

- Cars
    - Audi
         - Diesel
         - petrol
         - electric
    - VW
.....

maybe extend sortable view and store a parent

![sort](https://user-images.githubusercontent.com/34944934/45177021-081bdf80-b212-11e8-84af-31f94b1743eb.png)

**Comment by franzwilding** [comment]
- [ ] Implement parent field -> extends reference field
- [ ] Implement tree view that needs a parent field and a sort_index field
- [ ] Maybe for this we would need the reverse reference field
