### ISSUE TITLE
Reference Field should support multiple types

### ISSUE THREAD

**Issue by stefan-kamsker** [unite-cms/unite-cms#232]
Maybe i want to reference multiple Content Types with one single Reference field

**Comment by franzwilding** [comment]
In theory this is possible, this is also the reason why we save the domain and content_type to the field content and not the field settings. 

However, this can already be achieved by using the variants field so this is not very urgent in my opinion.

**Comment by franzwilding** [comment]
Can be done in 0.10 with Union Types
