### ISSUE TITLE
Section inside Section leads to 500er error

### ISSUE THREAD

**Issue by stefan-kamsker** [unite-cms/unite-cms#233]
seems to be a problem with reference field inside a collection

![bildschirmfoto 2018-09-06 um 15 23 20](https://user-images.githubusercontent.com/34944934/45160165-0e499600-b1e9-11e8-9828-39a832c5a6a2.png)
![section_inside_section_error](https://user-images.githubusercontent.com/34944934/45160153-07228800-b1e9-11e8-8b01-d1d8e242977e.png)

**Comment by franzwilding** [comment]
Problem is a self-referencing circle page references page -> ... I will fix this!
