### ISSUE TITLE
Implement a checkboxes Type

### ISSUE THREAD

**Issue by stefan-kamsker** [unite-cms/unite-cms#235]
imagine the following choice field, where we want to select multiple values

could be solved with a collection field but would result in a repeated config

```
{
   "title": "Disciplines",
    "identifier": "disciplines",
    "type": "choice",
    "settings": {
        "choices": {
            "choice1": "Choice 1",
            "choice2": "Choice 2",
            "choice3": "Choice 3"
        }
    }
}
```
maybe related to #231

**Comment by franzwilding** [comment]
Can already be implemented using a choice field inside a collection field
