### ISSUE TITLE
Improve Reference Field - inline edit 

### ISSUE THREAD

**Issue by stefan-kamsker** [unite-cms/unite-cms#238]
allow to add new content and delete content inline

imagine tags:
- should be reusable (content) for the domain or even further

would be cool to add new tags right on the reference field

![inline_reference_edit](https://user-images.githubusercontent.com/34944934/45177288-d6efdf00-b212-11e8-88ee-eaacc1eb671b.png)

**Comment by franzwilding** [comment]
Yes. At the moment, this can only be implemented at view level. The view would need to support inline create / edit or even file upload. 

Im going to create a new label "Views refactoring" where we can collect all of the Views tasks. I think this should be the next big feature we are going to implement

**Comment by franzwilding** [comment]
Plan from Workshop: 
- [ ]  Render a form (with configurable fields) on the view page to allow quick / inline edit. Maybe also inline edit?

**Comment by franzwilding** [comment]
Implemented in 0.10
