### ISSUE TITLE
Field Default Values & Form Required option

### ISSUE THREAD

**Issue by stefan-kamsker** [unite-cms/unite-cms#239]
At the moment we have no option to provide a default value for some fields

fe. choice field
<img width="354" alt="bildschirmfoto 2018-09-06 um 20 55 27" src="https://user-images.githubusercontent.com/34944934/45178880-44057380-b217-11e8-9da8-85fe85bbc8da.png">

Also implement symfony required option for suitable fields

**Comment by franzwilding** [comment]
This is a good idea, and easy to implement. However I will add it to the 0.7 milestone, because this is an API change.

**Comment by franzwilding** [comment]
Maybe implement in abstract class FieldType as setting (same as required option)
