### ISSUE TITLE
Should we allow the symfony required option (in addition to validations)?

### ISSUE THREAD

**Issue by stefan-kamsker** [unite-cms/unite-cms#240]
I know there are validations in unite cms which are very flexible :)

but for this simple setting, this seems overpowered to me

imagine a content type with 10 text fields and i just want to make all fields required, no special validation messages needed, just "Fieldname is required"

<img width="381" alt="required" src="https://user-images.githubusercontent.com/34944934/45179309-7794cd80-b218-11e8-8fe4-18825f9595a8.png">

**Comment by franzwilding** [comment]
If you want to implement a required flag for all fields then all fields need a custom implementation. For simple text / textarea fields that would be easy. But what about more complex fields like the collection field? What does required means for them? At least one row? Or all subfields should be required?

I like the idea to simplify validations, however we would need a more flexible solution. Maybe we could create some validation shortcuts like this: 

`{ "require": "data.headline" }`

which equals to: 

`{ "expression": "data.headline" != '', "path": "headline": "message": "This field is required" }`

This way, we would not lose flexibility

**Comment by stefan-kamsker** [comment]
shortcuts sound great

**Comment by stefan-kamsker** [comment]
closed in favour of #239
