### ISSUE TITLE
Select existing image/file from Bucket Image/File Field

### ISSUE THREAD

**Issue by stefan-kamsker** [unite-cms/unite-cms#244]
At the moment i can't select an existing image/file from S3 bucket, fe. if i want to use the same image multiple times.  The same image is getting stored multiple times. (would be a waste of space)

**Comment by franzwilding** [comment]
At the moment, we are solving this problem by creating a dedicated file (or media) content type that can referenced by other content types. 

Then you can reuse a single file. 

Creating a s3 selector would bring a large amount of complexity to the media module: 
1. What deleting content with a file, we would need to check all places, where the file was selected and warn the user about it
2. When updating a file, all other content with this file will get updated as well
3. Files in a s3 bucket can also be part of another application. Selecting existing files could have unwanted side effects on the other application.
