### ISSUE TITLE
Variables Same variable content

### ISSUE THREAD

**Issue by stefan-kamsker** [unite-cms/unite-cms#245]
fe. if i use the same name "domain1" for bucket name as the domain identifier, also domain identitfier is getting replaced with @minio_bucket on save, which is working but is confusing

![45253403-c3558d00-b366-11e8-99c8-15c8f80d44b7](https://user-images.githubusercontent.com/34944934/45254023-a1610800-b370-11e8-9cfb-afdd35846d08.png)

**Comment by franzwilding** [comment]
Actually, this is the way it is implemented at the moment: 

Each occurrence of the content of a variable will get replaced. We do not save the JSON (with variables at the moment), so this is the only possible way.

So for this example you can save the whole bucket information into one variable to avoid conflicts. 

In the future we can think of a more complex solution, where we also save the JSON (maybe also revertable versions). Then it is possible to have two variables with the same content

**Comment by stefan-kamsker** [comment]
maybe i often want a different bucket path for each image field (teasers, main images etc.), so the advantage would be gone

but prio is low

**Comment by franzwilding** [comment]
True, I think we need to improve variables in the future by save the JSON to the database. Maybe this also allows us to go back to another configuration or some other advanced features

**Comment by Clonk-HTML5** [comment]
would be perfect ran in the same Issue ;-)
For reuse some parts of the Configuration it would be perfect

**Comment by franzwilding** [comment]
Closed in favour of #246
