### ISSUE TITLE
Save domain config & variables in files

### ISSUE THREAD

**Issue by stefan-kamsker** [unite-cms/unite-cms#246]
it would be cool if a full field config would work with variables (with all fields), at the moment such a config is not replaced (i think because of image field, not supported at the moment)

```
{
    "title": "OG Metatags",
    "identifier": "ogmetatags",
    "type": "collection",
    "settings": "@og_meta_settings"
}

"@og_meta_settings": {
    "max_rows": "1",
    "fields": [
         {
                "type": "text",
                "identifier": "title",
                "title": "Title"
         },
         {
                "type": "textarea",
                "identifier": "description",
                "title": "Description"
         },
         {
                "title": "OG Image",
                "identifier": "ogimage",
                "type": "image",
                "settings": {
                  "bucket": {
                    "endpoint": "xxxx",
                    "bucket": "xxx",
                    "path": "ogImage",
                    "key": "xxx",
                    "secret": "xxx"
                  }
                }
         }
     ]
}
```

**Comment by franzwilding** [comment]
Actually this should work. There is no magic in variables but a simple string replace. One thing important when using variables: They must have the exact same structure (this also includes the order of keys) as in the domain config. 

For example, this is working: 
<img width="1125" alt="update domain blog tutorial 1 - unite cms 2018-09-10 08-46-56" src="https://user-images.githubusercontent.com/309309/45280809-231e7600-b4d6-11e8-894d-d2dbdcae0543.png">

Can you double check and report back?

**Comment by stefan-kamsker** [comment]
see #245

**Comment by franzwilding** [comment]
Plan from workshop: 

- [ ] Save json config to files
- [ ] Move variables config from DB to this file
- [ ] Read file json content on domain update into editor
- [ ] Save json config on domain update / save to file
- [ ] If there is a domain but no file: Create file
- [ ] If there is a file but no domain: Create domain
- [ ] Improve diff step
