### ISSUE TITLE
Is multilanguage supported ?

### ISSUE THREAD

**Issue by Clonk-HTML5** [unite-cms/unite-cms#247]
Is there a way to implement multilanguage support for the Content Types ?

thanks in advance

**Comment by Clonk-HTML5** [comment]
Perfekt Thanks, works great. Would it maybe possible to show the language in the List view ?

thanks in advance

**Comment by franzwilding** [comment]
Yes, this is possible. Just add it as a column to the view settings: 

    "views": [
        {
          "title": "All",
          "identifier": "all",
          "type": "table",
          "settings": {
            "columns": {
              "headline": "Headline",
              "created": "Created at",
              "locale": "Language"
            }
          }
        }
      ],

**Comment by stiffroy** [comment]
The setting of the `columns` under the `settings` is deprecated:
```
The child node "columns" at path "settings" is deprecated.
```
