### ISSUE TITLE
prevent use of an subdomain for the Profile Url profile.example.de

### ISSUE THREAD

**Issue by Clonk-HTML5** [unite-cms/unite-cms#251]
prevent use of an subdomain for the Profile url profile.example.de

thanks in advance

**Comment by Clonk-HTML5** [comment]
I think i found it in the .env File you can set ROUTING_APPROACH=parameter than it seems to work

**Comment by franzwilding** [comment]
You are right. With this parameter, you can change select the routing approach (sundomain, as we use it at unitecms.io) or first parameter (good for locale development).

I reopened the issue, because docs are missing.

**Comment by Clonk-HTML5** [comment]
Oh, i figured out that the Parameter Routing Approach is not really working i get a 404 Error when calling the startpage.
/profile/login

`[2018-09-13 12:57:24] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-09-13 12:57:24] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access denied. at /var/www/vhosts/topics.karls.cloud/topics.karls.cloud/vendor/sensio/framework-extra-bundle/EventListener/SecurityListener.php:78)"} []
[2018-09-13 12:57:24] security.DEBUG: Calling Authentication entry point. [] []`

**Comment by stefan-kamsker** [comment]
hi,

i'm also using ROUTING_APPROACH=parameter on my local setup
can't reproduce this, does a cache:clear fix the problem?

**Comment by Clonk-HTML5** [comment]
Hi,

i'm using the standard Edition cache cleared as well removed var cache Dir.
But the Problem still appear.
I'm using php Version 7.2.9.

`APP_ENV=dev
ROUTING_APPROACH=parameter
DATABASE_HOST=127.0.0.1
DATABASE_PORT=
DATABASE_NAME=test
DATABASE_USER=test
DATABASE_PASSWORD=0
MAILER_SENDER=developer@test.de
MAILER_URL=smtp://127.0.0.1:1025
`

**Comment by Clonk-HTML5** [comment]
With your Docker Setting it works.
I will check what's different in Docker and on my Server tomorrow.

**Comment by stefan-kamsker** [comment]
thank you, maybe there is something i can't reproduce right now
maybe a cookie clear does help

**Comment by Clonk-HTML5** [comment]
No cookie clear doesn't help.
A fresh install (on the same Server) also not helps maybe it has to with some Server Settings.

**Comment by franzwilding** [comment]
@Clonk-HTML5 Have you figured it out? Was cookie_domain causing the problem?

**Comment by Clonk-HTML5** [comment]
@franzwilding i still try to find the reason.
cookie_domain didn't solve it.
I just get the Error on my Server maybe it have something todo with the reason that php 7.0 cli is the Default php cli Version.
Docker Local installation is working fine.
I just checked my Server with the Symfony Requirements and all is fine.
I will try now to install it on an other Server for testing.
But the Main Code seems to work because i always get redirect to the /profile/login page but there i get a 404.

**Comment by Clonk-HTML5** [comment]
If i run the csm locally and run it with bin/console serve:run it works as well.

**Comment by Clonk-HTML5** [comment]
maybe it have something todo with plesk. Where do you host the Cloud Instance of unitecms ?

**Comment by Clonk-HTML5** [comment]
Yeah, i found the Issue:

Missing .htaccess file in public Folder.
use the [htaccess](https://raw.githubusercontent.com/symfony/recipes-contrib/master/symfony/apache-pack/1.0/public/.htaccess) from apache-pack and install the following:

```
composer config extra.symfony.allow-contrib true

composer req symfony/apache-pack
```

**Comment by franzwilding** [comment]
Glade to hear!

I think, we should write a little tutorial, how to set up unite cms (https://github.com/unite-cms/unite-cms/issues/259)
