### ISSUE TITLE
Content Type permission for translate Action

### ISSUE THREAD

**Issue by Clonk-HTML5** [unite-cms/unite-cms#252]
would it be possible to define an permission for the translate Action (to disable it for a few User : Editors)

 for example:

`"permissions": {
    "view content": "member.data.project_admin_for == content.project",
    "translate content": "member.type == \"editor\" or member.accessor.type == \"api_key\""
}`

**Comment by franzwilding** [comment]
Good idea! 

At the moment, translation checks for to the „update content“ permission. So everyone, who is allowed to update content can also translate it. 

We could implement an optional „translate content“ permission, that falls back to „update content“ if not defined.

**Comment by Clonk-HTML5** [comment]
Sounds good!
Thanks

**Comment by franzwilding** [comment]
If you want to, you can tr to implement this feature and create a pull request. Otherwise, wile will put it on the roadmap for v0.8.

**Comment by Clonk-HTML5** [comment]
Ok, i will give it a try ;-)

**Comment by franzwilding** [comment]
Cool :) But no worries, we will give you feedback and will step in, if you can't find time to finish this feature

**Comment by Clonk-HTML5** [comment]
perfect

**Comment by stefan-kamsker** [comment]
Hi @Clonk-HTML5,

during the implementation of this issue, i realized that it is not clear to me how the "update content" permission differs from the "translate content" permission. I think we should discuss options and use cases.

**What is your use case here?**
What should a user only with "translate content" permission be able to do in your opinion?

**Variants:**
1. A user with "translate content" permission has more permissions than a user with "update content" permission => Manage Translations (add new translations / update translations / remove translations / set existing content as translation)
2. A user with "translate content" permission has less permissions than a user with "update content" permission => fe. only create new content / set existing content as a translation

Thank you!

Best regards!

**Comment by Clonk-HTML5** [comment]
Hi @stefan-kamsker,

i think the second Variant is the most useful Variant.
Because if i want to add a Translator to the System he should only create translation nothing more.
It should also be possible to disable the creation of a Translation.

Thanks
Happy new Year ;-)

**Comment by Clonk-HTML5** [comment]
Hi,

that sounds like a good plan!
I have nothing further to add.

Thank you
