### ISSUE TITLE
Amazon S3 Image Select

### ISSUE THREAD

**Issue by Clonk-HTML5** [unite-cms/unite-cms#253]
Hey,

would it be possible to select an Image from a Amazon S3 Bucket ?
This would be a great Feature.

**Comment by Clonk-HTML5** [comment]
How is it possible to create a new content type ?
Best is to create a Bundle like the VariationBundle or ?

**Comment by franzwilding** [comment]
The Symfony Best Practices are: 

If the new field type is only part of your application, put in under namespace App\ (https://symfony.com/doc/current/best_practices/business-logic.html)

If you are planing to share this field type with others (for example publishing it on github), create a reusable bundle for it (https://symfony.com/doc/current/bundles/best_practices.html)
