### ISSUE TITLE
No Access to API Internal Server Error

### ISSUE THREAD

**Issue by Clonk-HTML5** [unite-cms/unite-cms#254]
Hey,

i have no Access to API i get an Internal Server Error.
On Cloud Server as well as on Local Docker Instance.
Could you have a look ?

https://{ORG}.unitecms.io/{DOMAIN}/api

On local:

http://localhost:8080/{ORG}/{DOMAIN}/api

On local i get following Error:

`Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: "No route found for "GET /karls/topics/api": Method Not Allowed (Allow: POST, OPTIONS)" at /app/unite-cms/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 143`

**Comment by franzwilding** [comment]
Our GraphQL API only works with HTTP POST and not HTTP GET. To explore the api, you can use https://github.com/graphql/graphiql or one of its browser plugin implementations: for example: https://chrome.google.com/webstore/detail/chromeiql/fkkiamalmpiidkljmicmjfbieiclmeij

**Comment by Clonk-HTML5** [comment]
Ok Thanks
