### ISSUE TITLE
Strange Behavior when deleting or updating Fields in Domain Config

### ISSUE THREAD

**Issue by Clonk-HTML5** [unite-cms/unite-cms#266]
Good Morning,

when i change f.e.:  a fields config of a collection field from an array to an array from the variables it seems not to save the variable.
If reload a few times and clear the array and save it again sometimes it works.

**Comment by franzwilding** [comment]
Hey! Can you post your domain config?

**Comment by Clonk-HTML5** [comment]
Domain Config:

`{
  "title": "Themen",
  "identifier": "topics",
  "content_types": [
    {
      "title": "Standorte",
      "identifier": "locations",
      "content_label": "{name}",
      "fields": [
        {
          "title": "Position",
          "identifier": "position",
          "type": "sortindex"
        },
        {
          "title": "Name",
          "identifier": "name",
          "type": "text"
        },
        {
          "title": "Standort Infos",
          "identifier": "location_infos",
          "type": "wysiwyg",
          "settings": "@wysiwyg_settings"
        },
        {
          "title": "Anzeige Name",
          "identifier": "display_name",
          "type": "text"
        },
        {
          "title": "Standort befindet sich bei:",
          "identifier": "location_by",
          "type": "text"
        },
        {
          "title": "Öffnungszeiten",
          "identifier": "oppening_hours",
          "type": "collection",
          "settings": {
            "min_rows": "1",
            "max_rows": "15",
            "fields": [
              {
                "type": "datetime",
                "identifier": "start_date",
                "title": "Startdatum"
              },
              {
                "type": "datetime",
                "identifier": "end_date",
                "title": "Enddatum"
              },
              {
                "type": "text",
                "identifier": "time_string",
                "title": "Zeitangabe"
              }
            ]
          }
        },
        {
          "title": "Straße / Hausnr.",
          "identifier": "street",
          "type": "text"
        },
        {
          "title": "PLZ / Ort",
          "identifier": "city",
          "type": "text"
        },
        {
          "title": "Telefonnr.",
          "identifier": "phone",
          "type": "text"
        },
        {
          "title": "Email",
          "identifier": "email",
          "type": "text"
        }
      ],
      "views": [
        {
          "title": "All",
          "identifier": "all",
          "type": "table"
        }
      ],
      "permissions": {
        "view content": "true",
        "list content": "true",
        "create content": "member.type == \"editor\"",
        "update content": "member.type == \"editor\"",
        "delete content": "member.type == \"editor\""
      }
    },
    {
      "title": "Erlebnisse",
      "identifier": "adventures",
      "content_label": "{headline} - {location.name}",
      "fields": "@topicFields",
      "views": [
        {
          "title": "All",
          "identifier": "all",
          "type": "table",
          "settings": {
            "columns": {
              "headline": "Headline",
              "created": "Created at",
              "locale": "Language"
            },
            "filter": {
              "field": "locale",
              "operator": "=",
              "value": "@default_local"
            }
          }
        }
      ],
      "permissions": {
        "view content": "true",
        "list content": "true",
        "create content": "member.type == \"editor\"",
        "update content": "member.type == \"editor\"",
        "delete content": "member.type == \"editor\""
      },
      "locales": "@locales"
    },
    {
      "title": "Manufakturen",
      "identifier": "factories",
      "content_label": "{type} #{id}",
      "fields": "@topicFields",
      "views": [
        {
          "title": "All",
          "identifier": "all",
          "type": "table"
        }
      ],
      "permissions": {
        "view content": "true",
        "list content": "true",
        "create content": "member.type == \"editor\"",
        "update content": "member.type == \"editor\"",
        "delete content": "member.type == \"editor\""
      }
    }
  ],
  "setting_types": [
    {
      "title": "Allgemein",
      "identifier": "general",
      "fields": [
        {
          "title": "Name",
          "identifier": "name",
          "type": "text"
        },
        {
          "title": "Datenschutz Text",
          "identifier": "data_protection_text",
          "type": "wysiwyg",
          "settings": "@wysiwyg_settings"
        },
        {
          "title": "Impressum Text",
          "identifier": "imprint_text",
          "type": "wysiwyg",
          "settings": "@wysiwyg_settings"
        }
      ],
      "permissions": {
        "view setting": "true",
        "update setting": "member.type == \"editor\""
      },
      "locales": "@locales"
    }
  ],
  "domain_member_types": [
    {
      "title": "Editor",
      "identifier": "editor",
      "domain_member_label": "{accessor}",
      "fields": []
    },
    {
      "title": "Viewer",
      "identifier": "viewer",
      "domain_member_label": "{accessor}",
      "fields": []
    }
  ],
  "permissions": {
    "view domain": "true",
    "update domain": "false"
  }
}`


Variables:

'{
  "@wysiwyg_settings": {
    "heading": [
      "h2",
      "h3",
      "p"
    ]
  },
  "@locations": [
    "Rövershagen",
    "Elstal",
    "Zirkow",
    "Warnsdorf",
    "Koserow",
    "Warnemünde",
    "Loburg"
  ],
  "@locales": [
    "de",
    "en",
    "pl"
  ],
  "@default_local": "de",
  "@bucketImage": {
    "endpoint": "https://s3.amazonaws.com",
    "bucket": "test",
    "path": "bilder",
    "key": "testse",
    "secret": "test"
  },
  "@bucketVideo": {
    "endpoint": "https://s3.amazonaws.com",
    "bucket": "test",
    "path": "videos",
    "key": "tes",
    "secret": "test"
  },
  "@prioritys": {
    "niedrig": "low",
    "mittel": "middle",
    "hoch": "high",
    "am höchsten": "highest"
  },
  "@topicFields": [
    {
      "title": "Priorität",
      "identifier": "priority",
      "type": "choice",
      "settings": {
        "choices": {
          "niedrig": "low",
          "mittel": "middle",
          "hoch": "high",
          "am höchsten": "highest"
        }
      }
    },
    {
      "title": "Standort",
      "identifier": "location",
      "type": "reference",
      "settings": {
        "domain": "topics",
        "content_type": "locations",
        "view": "all",
        "content_label": "{name}"
      }
    },
    {
      "title": "Tags (Kommasepariert)",
      "identifier": "tags",
      "type": "text"
    },
    {
      "title": "Überschrift",
      "identifier": "headline",
      "type": "text"
    },
    {
      "title": "Bild",
      "identifier": "image",
      "type": "image",
      "settings": {
        "bucket": {
          "endpoint": "https://s3.amazonaws.com",
          "bucket": "test",
          "path": "bilder",
          "key": "test",
          "secret": "test"
        }
      }
    },
    {
      "title": "Video",
      "identifier": "video",
      "type": "file",
      "settings": {
        "bucket": {
          "endpoint": "https://s3.amazonaws.com",
          "bucket": "test",
          "path": "videos",
          "key": "test",
          "secret": "test"
        }
      }
    },
    {
      "title": "Beschreibung",
      "identifier": "description",
      "type": "wysiwyg",
      "settings": {
        "heading": [
          "h2",
          "h3",
          "p"
        ]
      }
    },
    {
      "title": "Inhalte",
      "identifier": "content",
      "type": "collection",
      "settings": {
        "min_rows": "1",
        "max_rows": "15",
        "fields": [
          {
            "title": "Inhaltstypen",
            "identifier": "content_types",
            "type": "variants",
            "settings": {
              "variants": [
                {
                  "title": "Text",
                  "identifier": "text",
                  "description": "Ein normaler Text",
                  "icon": "file-text",
                  "fields": [
                    {
                      "title": "Text",
                      "identifier": "text",
                      "type": "text"
                    }
                  ]
                },
                {
                  "title": "Bild und Text",
                  "identifier": "image_and_text",
                  "description": "Bild und Text",
                  "icon": "image",
                  "fields": [
                    {
                      "title": "Text",
                      "identifier": "text",
                      "type": "text"
                    },
                    {
                      "title": "Bild",
                      "identifier": "image",
                      "type": "image",
                      "settings": {
                        "bucket": {
                          "endpoint": "https://s3.amazonaws.com",
                          "bucket": "test",
                          "path": "bilder",
                          "key": "test",
                          "secret": "test"
                        }
                      }
                    }
                  ]
                },
                {
                  "title": "Video",
                  "identifier": "video",
                  "description": "Eine Video-Datei",
                  "icon": "video",
                  "fields": [
                    {
                      "title": "Video",
                      "identifier": "video_file",
                      "type": "file",
                      "settings": {
                        "bucket": {
                          "endpoint": "https://s3.amazonaws.com",
                          "bucket": "test",
                          "path": "videos",
                          "key": "test",
                          "secret": "test"
                        }
                      }
                    }
                  ]
                }
              ]
            }
          }
        ]
      }
    },
    {
      "title": "Bilder Slider",
      "identifier": "image_slider",
      "type": "collection",
      "settings": {
        "fields": [
          {
            "title": "Bild",
            "identifier": "slider_image",
            "type": "image",
            "settings": {
              "bucket": {
                "endpoint": "https://s3.amazonaws.com",
                "bucket": "test",
                "path": "bilder",
                "key": "test",
                "secret": "testes"
              }
            }
          }
        ]
      }
    },
    {
      "title": "Bilder Gallerie",
      "identifier": "image_gallery",
      "type": "collection",
      "settings": {
        "fields": [
          {
            "title": "Bild",
            "identifier": "gallery_image",
            "type": "image",
            "settings": {
              "bucket": {
                "endpoint": "https://s3.amazonaws.com",
                "bucket": "test",
                "path": "bilder",
                "key": "test",
                "secret": "test"
              }
            }
          }
        ]
      }
    }
  ]
}'

**Comment by stefan-kamsker** [comment]
i can confirm this bug with another domain config

**Comment by franzwilding** [comment]
@stefan-kamsker can you show me the other config?

**Comment by stefan-kamsker** [comment]
@franzwilding config is huge, i wrote you

**Comment by franzwilding** [comment]
@stefan-kamsker & @Clonk-HTML5 a few infos about the current (experimental) implementation of variables: 

- We do not save the domain config (with variables), the config is serialized from the domain entity (PHP object) every time, you open the update domain page
- After serialization is done, we iterate over all defined variables and do a simple string replace on the domain config with the variable content (and on save visa-vi)
- The first match of a variable content in the domain config will get replaced
- Variables in variables do not work at the moment

So for examples this domain config: 

    { "locales": ["foo", "baa"] }

With this variables: 

    @var1: "foo",
    @var2: ["foo", "baa"]

Will result in:

    { "locales": ["@var1", "baa"] }

We will improve the variables in one of the next releases and allow a real variables behaviour. For this to work however, we need to save the domain config (with all variables) to the database, so this is a bigger change. 

Does this solve your problem @Clonk-HTML5 ? If not, please help me to reproduce your exact situation by providing more information.

**Comment by Clonk-HTML5** [comment]
Ok, thanks for tell us about the internal handling.
I get it to work, with just delete the the Content Types where the Problem appears and then add the types again.
