### ISSUE TITLE
Variation Type returns always null in Graphql

### ISSUE THREAD

**Issue by Clonk-HTML5** [unite-cms/unite-cms#274]
The Variation Type returns in Graphql always  returns null.

Example:

`{
  findAdventures {
    result {
      id
      locale
      content {
        content_types {
          type,
          ... on AdventuresContentContentContent_typesTextVariant {
            text
          }
          ... on AdventuresContentContentContent_typesImage_and_textVariant {
            text
          }
        }
      }
    }
  }
}
`

Result:

`{
  "data": {
    "findAdventures": {
      "result": [
        {
          "id": "1252c64a-bb3c-11e8-a901-d87bdfebfe37",
          "locale": "de",
          "content": [
            {
              "content_types": null
            },
            {
              "content_types": null
            },
            {
              "content_types": null
            }
          ]
        },
        {
          "id": "3969c989-bb3d-11e8-a901-d87bdfebfe37",
          "locale": "de",
          "content": [
            {
              "content_types": null
            }
          ]
        },
        {
          "id": "f15a36ea-bb44-11e8-a901-d87bdfebfe37",
          "locale": "en",
          "content": []
        }
      ]
    }
  }
}`

**Comment by stefan-kamsker** [comment]
hi,

can you please paste your config?
yours seem more nested eg. "AdventuresContentContentContent_typesTextVariant "

the example from the docs is working https://www.unitecms.io/docs.html

thx

**Comment by Clonk-HTML5** [comment]
Hey,

here is my Config it's nested in a Collection:

       {
          "title": "Inhalte",
          "identifier": "content",
          "type": "collection",
          "settings": {
            "min_rows": "0",
            "max_rows": "15",
            "fields": [
              {
                "title": "Inhaltstypen",
                "identifier": "content_types",
                "type": "variants",
                "settings": {
                  "variants": [
                    {
                      "title": "Text",
                      "identifier": "text",
                      "description": "Ein normaler Text",
                      "icon": "file-text",
                      "fields": [
                        {
                          "title": "Text",
                          "identifier": "text",
                          "type": "text"
                        }
                      ]
                    },
                    {
                      "title": "Bild und Text",
                      "identifier": "image_and_text",
                      "description": "Bild und Text",
                      "icon": "image",
                      "fields": [
                        {
                          "title": "Text",
                          "identifier": "text",
                          "type": "text"
                        },
                        {
                          "title": "Bild",
                          "identifier": "image",
                          "type": "image",
                          "settings": {
                            "bucket": "@bucketImage"
                          }
                        }
                      ]
                    },
                    {
                      "title": "Video",
                      "identifier": "video",
                      "description": "Eine Video-Datei",
                      "icon": "video",
                      "fields": [
                        {
                          "title": "Video",
                          "identifier": "video_file",
                          "type": "file",
                          "settings": {
                            "bucket": "@bucketVideo"
                          }
                        }
                      ]
                    }
                  ]
                }
              }
            ]
          }
        },

**Comment by franzwilding** [comment]
@stefan-kamsker Can you check and fix it? If it is a real bug, we should fix it with the 0.6.3 release

**Comment by Clonk-HTML5** [comment]
Thanks, it works ;-)
