### ISSUE TITLE
sortable table has no column header

### ISSUE THREAD

**Issue by STyle982** [unite-cms/unite-cms#275]
When the view type is set to "sortable" the the columns name won't show up any more.
```javascript
...
"views": [
  {
    "title": "All",
    "identifier": "all",
    "type": "sortable",
    "settings": {
      "sort_field": "position",
      "columns": {
        "name": "Name"
      }
    }
  }
],
...
```
The column name should be "Name" but it doesn't show it. It's Empty. Only "Sort" and "Action" are displayed.

![bildschirmfoto 2018-09-19 um 14 40 25](https://user-images.githubusercontent.com/2213427/45754580-4fe03500-bc1c-11e8-9988-5de64bfbd421.png)

**Comment by stefan-kamsker** [comment]
thank, yes, column name is not displayed at the moment

**Comment by franzwilding** [comment]
Hey @STyle982!

Thank you for the issue. We we refactor the whole table and sort view in version 0.7, so please be patient, it is the next big topic on our roadmap.
