### ISSUE TITLE
Sortable view is glitching

### ISSUE THREAD

**Issue by STyle982** [unite-cms/unite-cms#276]
When an element switch places the other elements keeps aligning left. Its very hard to keep track, where the element is moved for the editor. See GIF

![unite-cms_bug_1](https://user-images.githubusercontent.com/2213427/45761859-604cdb80-bc2d-11e8-8844-dbd0d04e6acb.gif)

**Comment by franzwilding** [comment]
Thx! This is also part of the views refactoring feature of v. 0.7
