### ISSUE TITLE
Extend Checkbox for multiple Checkboxes

### ISSUE THREAD

**Issue by Clonk-HTML5** [unite-cms/unite-cms#288]
Hi,

would it be possible to Extend the Checkbox for multiple Checkboxes per Field.
I just want to do something like this:

![bildschirmfoto 2018-09-25 um 13 37 42](https://user-images.githubusercontent.com/5723577/46012077-447f8480-c0c8-11e8-8bc5-372ff2b725b1.png)

**Comment by stefan-kamsker** [comment]
Hi,

yes, this is not allowed for the current choice type

we would do an additional "choices" type for this
set this at the roadmap for 0.7

you can give it a shot, if you don't want to wait :)

Best regards

**Comment by Clonk-HTML5** [comment]
Hi,

why just activate multiple ?
It just works out of the Box.
Should I make a Pull Request for enable it?
I get it to work on my Machine

**Comment by franzwilding** [comment]
Yes, Please make a PR and we will have a look!
