### ISSUE TITLE
local asset storage? 

### ISSUE THREAD

**Issue by voordev** [unite-cms/unite-cms#293]
Are there any plans to store assets ( images ) for example on the local file system where unitecms runs? 

I would like to store assets locally and not yet use AWS or S3. 
To reduce cost and keep things simple.

I could not find a reference in the documentation on how to set this up, if possible at all.

**Comment by franzwilding** [comment]
We are doing this with a locale minio instance (https://www.minio.io). We will provide a short tutorial in the next few days.

**Comment by franzwilding** [comment]
@voordev Is using minio a suitable solution for you?

**Comment by evanbarter** [comment]
I can't speak for @voordev, nor have I looked too hard at your Storage Bundle, but could storage be abstracted via [Flysystem](http://flysystem.thephpleague.com/docs/)?

**Comment by stefan-kamsker** [comment]
Hi,

thanks, we will have a look!

At the moment, we are not planning to implement a local asset handling in core.
It could be achieved by writing a own bundle and a own file / image type.

We will implement some addational providers #300 soon.

Best regards!

**Comment by franzwilding** [comment]
@voordev so running a minio instance will not work for you? Do you have a shard webhost and can't run minio, or why is the current solution not working for you?

**Comment by voordev** [comment]
To complex for my usecase will look at another solution local dtprage is a must for simple sites to keep it lean without whole tevhnical stack like aws

**Comment by fr0tt** [comment]
@stefan-kamsker This feature would be much appreciated!

**Comment by maheraldous** [comment]
Any news about the local file storage and the ability to upload images to the local storage via GraphQL? @franzwilding
