### ISSUE TITLE
Webhooks Post optional declare Content-Typ of Form Data Enhancement 

### ISSUE THREAD

**Issue by Clonk-HTML5** [unite-cms/unite-cms#310]
Hi,

this is just a small Enhancement but in some cases useful in the Webhooks it should be possible to set an optional Property to declare Content-Typ of the Form Data.
Default could be stay to JSON.

f.e.:

```javascript
"webhooks": [
        {
          "query": "@default_translation_query",
          "url": "@default_translation_query_url",
          "check_ssl": true,
          "content_type": "form_data",
          "condition": "@default_translation_query_condition"
        }
      ]
```

**Comment by stefan-kamsker** [comment]
Hi,

yes, thanks, at the moment it's json only, should be configurable

Best regards!
