### ISSUE TITLE
CSRF token is invalid

### ISSUE THREAD

**Issue by Clonk-HTML5** [unite-cms/unite-cms#318]
Hi,

i get an Issue with saving any Content Type.
Following Error occurred:
The CSRF token is invalid. Please try to resubmit the form.

**Comment by Clonk-HTML5** [comment]
I just logout clear Application Data and then saving works again.
Do you know whats the Issue in this case ?

**Comment by stefan-kamsker** [comment]
Hi,
we'll investigate if theres a problem

**Comment by Clonk-HTML5** [comment]
I just saw that if the Session exceded.
The current Backenduser gots not loggout.
And if the User saves something in this case the Error Appears.

**Comment by stefan-kamsker** [comment]
hi,
thanks for the help!
so the user should be logged out automatically (or there should be a notice) if the sessions was exceeded

**Comment by franzwilding** [comment]
@Clonk-HTML5 
Can you tell us how to reproduce this?

**Comment by Clonk-HTML5** [comment]
It appears if the Session exceeded.
I'am still logged in and try to create / update content.
Then this Error is display above the form.

**Comment by franzwilding** [comment]
Thank you! I think I found the bug. We only set the session lifetime but not the cookie lifetime.
