### ISSUE TITLE
Mutation with Type 'StorageFileInput'

### ISSUE THREAD

**Issue by STyle982** [unite-cms/unite-cms#323]
I cant figure out how to insert AWS S3 Images to unite-cms from outside (API).
The Problem is, that I must declare the ID and a checksum. But how can I add a checksum or id, when its created by unite-cms?

![bildschirmfoto 2018-10-11 um 11 04 02](https://user-images.githubusercontent.com/2213427/46793353-cbc62c80-cd45-11e8-8672-d6040c463a64.png)

**Comment by franzwilding** [comment]
Hey @STyle982 !

At the moment, the storage field can only upload new files. For this the client first has to make a call to  /{domain}/api/storage/sign/content/{content_type}/upload to get a pre_signed upload url and a checksum. In the second step, the client can set the StorageFileInput to upload the file. 
 
Is it clear now for you?

**Comment by STyle982** [comment]
Thanks for your response.
I tried, but I failed.

## Status Code: 405 Method Not Allowed
### Internal Server Error
An internal server error occurred. Please try again later. We are monitoring this error and will work on a solution.

Go to dashboard / login
___

The Data I passed to this url
`https://localhost/{organistation}/{domain}/api/storage/sign/content/{content_type}/upload`
where following:
```javascript
let data = new FormData();
data.append('pre_sign_form[filename]', file.name.replace(/\//g,''));
data.append('pre_sign_form[field]', file.path);
```
The Header contained `Authorization` with the API Key.
What do i send with the Token?
```javascript
data.append('pre_sign_form[_token]', ?);
```

**Comment by franzwilding** [comment]
Are you using the correct HTTP method (post)? 

You only need to set the (csrf) _token Field if you use cookie authentication (only usecase is when using the unite cms admin form). So when you pass the auth.  key in the header, no _token is required

**Comment by franzwilding** [comment]
Hey @STyle982 ! There was a problem, I fixed now (missing OPTIONS method) and here is a little tutorial including sample code, how to upload files via API: https://medium.com/unite-cms/unite-cms-s3-fileupload-via-graphql-api-191c1f505272
