### ISSUE TITLE
Scrollbar is appearing

### ISSUE THREAD

**Issue by stefan-kamsker** [unite-cms/unite-cms#332]
![bildschirmfoto 2018-10-16 um 14 00 41](https://user-images.githubusercontent.com/34944934/47015196-9f971b00-d14c-11e8-9a80-609bc1486adb.png)

**Comment by franzwilding** [comment]
@stefan-kamsker can u try: 
- checkout master
- dump assets again
- clear browser cache

If this dies not solve this problem, please post the domain config for this content type.

THX!

**Comment by stefan-kamsker** [comment]
is fixed 👍
