### ISSUE TITLE
S3 Storage bundle check if region can be null on aws php sdk config

### ISSUE THREAD

**Issue by stefan-kamsker** [unite-cms/unite-cms#333]

**Comment by stefan-kamsker** [comment]
**Unfortunately not:**
InvalidArgumentException: Missing required client configuration options:

region: (string)

  A "region" configuration value is required for the "s3" service
  (e.g., "us-west-2"). A list of available public regions and endpoints can be
  found at http://docs.aws.amazon.com/general/latest/gr/rande.html.

**Comment by franzwilding** [comment]
Then just live with us-east-1 as fallback. Can we close it @stefan-kamsker
