### ISSUE TITLE
PHP Fatal error:  Uncaught Symfony\Component\Dotenv\Exception\PathException

### ISSUE THREAD

**Issue by gigafactor** [unite-cms/unite-cms#342]
I managed to install everything until the environment variables. I am trying to finish the install of "unite cms production environment". Can you help me? What do I need to add to /etc/environment for this to work or I am looking at this completely wrong? Please bear with me I know this is a silly problem and I should know but I am tired of trying different things and nothing is working...

When I try to run any command of this three
`bin/console assets:install — env=prod
bin/console doctrine:schema:update — force — env=prod
bin/console cache:clear — env=prod`
I get the error:
`PHP Fatal error:  Uncaught Symfony\Component\Dotenv\Exception\PathException: Unable to read the "/home/user/unitecms/bin/../.env" environment file. in /home/user/unitecms/vendor/symfony/symfony/src/Symfony/Component/Dotenv/Dotenv.php:54
Stack trace:
#0 /home/user/unitecms/bin/console(22): Symfony\Component\Dotenv\Dotenv->load('/home/user/unit...')
#1 {main}
  thrown in /home/user/unitecms/vendor/symfony/symfony/src/Symfony/Component/Dotenv/Dotenv.php on line 54
user@VPS1:~/unitecms$`

I tired to change persmissions on files and folders /unitecms/bin and Dotenv.php and tried to add to /etc/environment home/user/unitecms/bin and /usr/local/unitecms/bin without any success...

System info (lsb_release -a):
`Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic`

php -v
`PHP 7.2.11-2+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Oct 15 2018 11:40:35) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.11-2+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
`
php --ini
`Configuration File (php.ini) Path: /etc/php/7.2/cli
Loaded Configuration File:         /etc/php/7.2/cli/php.ini
Scan for additional .ini files in: /etc/php/7.2/cli/conf.d
Additional .ini files parsed:      /etc/php/7.2/cli/conf.d/10-opcache.ini,
/etc/php/7.2/cli/conf.d/10-pdo.ini,
/etc/php/7.2/cli/conf.d/15-xml.ini,
/etc/php/7.2/cli/conf.d/20-calendar.ini,
/etc/php/7.2/cli/conf.d/20-ctype.ini,
/etc/php/7.2/cli/conf.d/20-dom.ini,
/etc/php/7.2/cli/conf.d/20-exif.ini,
/etc/php/7.2/cli/conf.d/20-fileinfo.ini,
/etc/php/7.2/cli/conf.d/20-ftp.ini,
/etc/php/7.2/cli/conf.d/20-gettext.ini,
/etc/php/7.2/cli/conf.d/20-iconv.ini,
/etc/php/7.2/cli/conf.d/20-json.ini,
/etc/php/7.2/cli/conf.d/20-mbstring.ini,
/etc/php/7.2/cli/conf.d/20-phar.ini,
/etc/php/7.2/cli/conf.d/20-posix.ini,
/etc/php/7.2/cli/conf.d/20-readline.ini,
/etc/php/7.2/cli/conf.d/20-shmop.ini,
/etc/php/7.2/cli/conf.d/20-simplexml.ini,
/etc/php/7.2/cli/conf.d/20-sockets.ini,
/etc/php/7.2/cli/conf.d/20-sysvmsg.ini,
/etc/php/7.2/cli/conf.d/20-sysvsem.ini,
/etc/php/7.2/cli/conf.d/20-sysvshm.ini,
/etc/php/7.2/cli/conf.d/20-tokenizer.ini,
/etc/php/7.2/cli/conf.d/20-wddx.ini,
/etc/php/7.2/cli/conf.d/20-xmlreader.ini,
/etc/php/7.2/cli/conf.d/20-xmlwriter.ini,
/etc/php/7.2/cli/conf.d/20-xsl.ini
`
Let me know if you need any additional info from me. Thanks for you help.

**Comment by stefan-kamsker** [comment]
Hi, 

depends

is this a local development setup or production? From your commands it seems like a production setup.

At the moment we have 2 setup guides:
https://www.unitecms.io/docs.html
https://medium.com/unite-cms/how-to-setup-unite-cms-for-local-development-or-on-a-production-server-c1da99fa5c90

on a production server you would set up /etc/environment etc. but i would recommend to set this on a user level, if possible, see the tutorial above.

Nevertheless it should work also with the .env file (but it isn't recommended)
Your path seems somehow wrong, normaly the .env would be located here /home/user/unitecms/.env

Unable to read the "/home/user/unitecms/bin/../.env" 

Best regards!
Stefan

**Comment by gigafactor** [comment]
Thank you for your response. This is a production server as noted above. I was looking at your guides but I am not seeing any example how to setup /etc/environment. Can you give me an example please. I only have one user named user that should be able to do everything.
Thanks!

**Comment by stefan-kamsker** [comment]
Maybe only the commands where wrong :)
it's wrong due to some formatting in the medium tutorial, sry, check thy hyphens

```
bin/console assets:install --env=prod
bin/console doctrine:schema:update --force --env=prod
bin/console cache:clear --env=prod
```

**Comment by gigafactor** [comment]
Thanks. I managed to get pass that error. 
Now I am stuck at
`bin/console doctrine:schema:update --force --env=prod`

Any advice. I am out of ideas. I am tired of trying to making this work without any success... 
Where do I need to change settings for proper connection to mysql database and unitecms?

user@VPS1:~/unitecms$ bin/console doctrine:schema:update --force --env=prod
`18:22:34` ERROR     [console] Error thrown while running command "doctrine:schema:update --force --env=prod". Message: "An exception occurred in driver: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'" ["exception" => Doctrine\DBAL\Exception\DriverException { …},"command" => "doctrine:schema:update --force --env=prod","message" => "An exception occurred in driver: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'"]

In AbstractMySQLDriver.php line 126:

  An exception occurred in driver: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'

In PDOConnection.php line 50:

  SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'

In PDOConnection.php line 46:

  SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'

doctrine:schema:update [--complete] [--dump-sql] [-f|--force] [--em [EM]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>`

**Comment by franzwilding** [comment]
You need to set the database config. This (as the question before) are general symfony topics. We will try to help you, however you can just google something like „symfony set up database“ or „symfony env Setup“ to find useful resources like 

https://symfony.com/doc/current/doctrine.html

For the moment, I will close this ticket, but once you setup a database connection and need further help, feel free to come back and open another issue. 

FYI: There is also a symfony slack channel, where you can get help with general symfony topics

**Comment by gigafactor** [comment]
I am still lost and people on symfony slack channel are not helpful sadly.
The only thing I am really sad about is that the guides/docs you have are missing a big part of the installation. 
I am that kind of person that would like to install unite cms from scratch on a server to test the performance and how does it handle but I do not install cms every day. It's been a while since I installed one actually but I still remember the general idea how to do it.
When I started installing I had to search for solutions for hours to get to the point until I opened this issue. I did not want to open it because I should know how to do this but after hours of trying you just get tired of not finding a proper solution.
How hard is to make a complete guide from scratch to install unite cms on clean ubuntu server (all commands) for people like me that like to have an example how to do everything. I was looking everywhere for this kind of guide but I guess unitecms it's still too new for someone to do this.
Installing this is probably total of 15 commands and changing some configuration files but if you do not know exactly what to change it might take forever to install.
Anyway thanks for your help so far and I will keep trying to get this to work...

**Comment by stefan-kamsker** [comment]
Hi, 

sad to hear that nobody is helping you out.

Yes, we are assuming that people have some knowledge in setting up symfony and have knowledge in server administration with this particular stack (PHP, nginx/apache, mysql).
There are simply to much different possibilities to host unite cms. (different linux distros, root server, managed server, cheap webspaces, cloud hosting, docker etc.). I would end up writing a lot of tutorials. 

I really encourage you to get familiar with all those things, especially when you want to run unite cms on a production root server. (think of security)
You'll likely run into problems again, fe. with updating unite cms.

For your Problem:

I think you didn't create a mysql database for unite cms or have some connection issues (wrong username / password)

you can create the database with 

`bin/console doctrine:database:create`

before those 3 commands

or create it by hand first

`CREATE DATABASE [databasename] CHARACTER SET utf8 COLLATE utf8_general_ci`

Best regards!
