### ISSUE TITLE
Reverse References Field Type

### ISSUE THREAD

**Issue by franzwilding** [unite-cms/unite-cms#355]
Implement a field type that does not store any content but allows to access content, that is referencing this content. 

Example settings on an example article content type: 
```json
{
    "title": "Comments",
    "identifier": "comments",
    "type": "reference_of",
    "settings": {
        "domain": "community",
        "content_type": "comments",
        "reference_field": "article"
    }
}
```
This would allow us to access all comments for an article, where the field "article" is set to this article.

Maybe our comments also can be nested, for this we would have another reference field on the comment content type with a reference to the parent comment and a reference_of field: 

```json
{
    "title": "Child Comments",
    "identifier": "children",
    "type": "reference_of",
    "settings": {
        "domain": "community",
        "content_type": "comments",
        "reference_field": "parent"
    }
}
```

**Comment by franzwilding** [comment]
This is an required for the tree sort ticket (#231)

**Comment by franzwilding** [comment]
@stefan-kamsker for this I would need the ID of the current content object. What do you think about passing the whole fieldablecontent object to the fieldable form and all child form elements can access it? This would also solve your initial_data problem. If you like the idea, you could implement it in your PR for version 0.7

**Comment by stefan-kamsker** [comment]
hi, yes, i would also make my life easier, will try
