### ISSUE TITLE
security issue found in login

### ISSUE THREAD

**Issue by Benedict-Lojewski** [unite-cms/unite-cms#356]
On login when the form is submitted, the password is readable in the login POST request.

`http://127.0.0.1:8080/profile/login`

What to see:
```
Formdata:

_username: lojewski@karls.de
_password: password
_remember_me: on
```

It should be encrypted or hashed before send over the network.

**Comment by stefan-kamsker** [comment]
Hi,

i would recommend a SSL certificate on a production server, it's risky otherwise.
Also some big other CMS systems have no protection here.

but we will check it!

Best regards!

**Comment by franzwilding** [comment]
I would also say that a public key protection is the only possible solution here and already implemented into TLS (HTTPS).

Do you have any suggestion, how we could improve security here?

**Comment by Benedict-Lojewski** [comment]
Maybe use an one-way encrypt algorithm on client side. So that the attacker doesn't have the plaintext password. This means we potentially save the user, who is highly likely using the same password across a number of services. The attacker can still replay request with encoded password but he don't know whats behind the password. On server side the password needs to be encrypted the same way as on client side to compare those two.

**Comment by franzwilding** [comment]
Do you have examples of (web)-applications that do it this way?

**Comment by Benedict-Lojewski** [comment]
No I don't. I read a bit more about this topic and the majority of them said that HTTPS is enough to keep the password encrypted. So don't mind my precipitation ticket request 😄

**Comment by franzwilding** [comment]
Ok! Then I will close this issue for now. But thanks for your input anyway. It is important to continuously rethink security.
