### ISSUE TITLE
Problem with type datetime

### ISSUE THREAD

**Issue by Benedict-Lojewski** [unite-cms/unite-cms#364]
I found a problem with type `datetime`.
When I set the `datetime` and submit the value, it is properly saved in database. But now when I want to update the content, the `datetime` is not set. See images below.

### before submit
![bildschirmfoto 2018-11-12 um 15 06 37](https://user-images.githubusercontent.com/44462588/48352307-b584f680-e68c-11e8-8ef9-293d9f5615c4.png)

### after click on update
![bildschirmfoto 2018-11-12 um 15 06 50](https://user-images.githubusercontent.com/44462588/48352346-cc2b4d80-e68c-11e8-9891-4a4ad2b569fa.png)

As you can see, the `datetime` is not loaded.
I added a normal `date` above it and this contains the saved date.

**Comment by Benedict-Lojewski** [comment]
It looks like the values are properly loaded, but it does't render.
```html
<input type="datetime-local" id="fieldable_form_end" name="fieldable_form[end]" required="required" class="uk-input" value="2018-11-12T12:00:00Z">
```
When I tried to read the value with console it shows it's empty (`""`). Its only filled when i reselect the date and time, then the console shows that the input value is set (`"2018-11-12T12:00"`)

**Comment by stefan-kamsker** [comment]
hi, 
thx, we will check it, looks like a bug
Best regards!

**Comment by franzwilding** [comment]
hey @Benedict-Lojewski!

I think this is related to https://github.com/symfony/symfony/pull/28372 I fixed it there. I will have a look, why this problem still remains in unite cms

**Comment by franzwilding** [comment]
@Benedict-Lojewski 

The PR, I started on the symfony project to fix this issue was merged into symfony 10 days ago. Starting with version 4.1.7, this problem is fixed now. Just run composer update :)
