### ISSUE TITLE
collection enhancement

### ISSUE THREAD

**Issue by Benedict-Lojewski** [unite-cms/unite-cms#365]
#351 
It would be nice when there is a way to collapse some collection content. I have an example below, where the collection field is a bit long. For the editor it's a pain in the a** to change the arrangement via drag and drop. 

Maybe I come to a better idea that can be used to make an extreme long collection more maintainable for the editor and that he becomes a better overview over such long lists.

![image](https://user-images.githubusercontent.com/44462588/48360420-7a3ff300-e69f-11e8-8fd0-71f9b21df7e2.png)

**Comment by stefan-kamsker** [comment]
hi, 
good idea!
Best regards!

**Comment by Benedict-Lojewski** [comment]
I got a good idea how we can make it more maintainable and sortable for nested long collection fields.
I designed my idea rough bellow but I will explain it a little bit.

How about a small representation of the collection on the side, that fits perfectly in view, when the collection is bigger than tripple view height or something. All collection elements should become a number to reference it in the small preview. The red rectangle indicates the current view port of the collection and moves when the user scrolls down the 'real' collection. All Elements are drag&drop capable. The green line indicates where the element would be dropped when released. This would make reorder for the editor more viewable, because he has all elements in one view and only needs to check the numbers that needs to be rearranged. 

![collection sort example](https://user-images.githubusercontent.com/44462588/48404921-9db37e00-e731-11e8-97b2-ce92dad1b0fb.png)
(This is only a sketch and can be modified)

What do you think about this idea @franzwilding?

**Comment by franzwilding** [comment]
I like the idea, dropbox paper has a similar menu on the left side: (
![image](https://user-ima) ges.githubusercontent.com/309309/48537384-c3679100-e8b1-11e8-8d1e-d6b19b7a9b7d.png)

You can't drag drop there but at least see the document structure.
