### ISSUE TITLE
Migrations instead of doctrine:schema:update --force

### ISSUE THREAD

**Issue by NMathar** [unite-cms/unite-cms#384]
Hi all,

btw really nice project. I think this is gone make my webdev life much easier. 

One question is there a plan to use doctrine migrations instead of schema update force? Or how you plan to update database schemas in the future? 

Regards Nico

**Comment by stefan-kamsker** [comment]
Hi, 

thanks, nice to hear!

Yes, it is planned to switch to doctrine migrations in the near future.

Best regards!

**Comment by NMathar** [comment]
Thank you!

**Comment by franzwilding** [comment]
We will switch to doctrine migrations when doctrine:schema:update will not work anymore. Until now there are only additions or changes to the database, that will not lead to data loses, so doctrine:schema:update is fine for the moment.
