### ISSUE TITLE
Add a possibility to delete a old domain config file from unite interface

### ISSUE THREAD

**Issue by stefan-kamsker** [unite-cms/unite-cms#386]
**scenario:**
i made a typo in domain identifier and i corrected it, the old domain config json stays and i have no option (at least i found none without losing the content) to delete the old domain config json file from the unite cms interface

![domain_change](https://user-images.githubusercontent.com/34944934/48720877-006cb400-ec21-11e8-9ed1-095f22fd48ae.png)
![2018-11-19](https://user-images.githubusercontent.com/34944934/48720876-006cb400-ec21-11e8-9818-bee43ac94207.png)

**Comment by franzwilding** [comment]
Will be fixed in https://github.com/unite-cms/unite-cms/pull/396. The domain config file name is now also synced on domain identifier update. So in your case wine_shop.json will be renamed to wine_shop1.json
