### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by NMathar** [unite-cms/unite-cms#392]
Hi Unite-Team,

i always get the 401 Unauthorized message if i want to authenticate with header information. With get token it works fine but Header is not working. I checked the header data in another php file and it looks  good. 

Any hints what i am doing wrong? 

`
Request Header
accept: */*
authorization: TOKEN-STRING
content-type: application/json
Origin: http://localhost:8080
Referer: http://localhost:8080/
` 

Regards Nico

**Comment by franzwilding** [comment]
We search for the header in `$request->headers->get('Authorization')`. I think symfony normalizes cases, but can you try setting Authorization with first char uppercase and whole string uppercase?

**Comment by NMathar** [comment]
No luck :( but i know now that the function  
`public function getCredentials(Request $request)` on auth with header is never called. With get token the function is called.

**Comment by franzwilding** [comment]
Can you debug `UniteCMS\CoreBundle\Security\ApiKeyAuthenticator` and check what header values are available in 

```php
/**
     * @param Request $request
     *
     * @return bool
     */
    public function supports(Request $request)
    {
        return $request->headers->has('Authorization') || $request->query->has('token');
    }
```

**Comment by NMathar** [comment]
I got it :face_with_head_bandage: for production settings these lines are needed in apache config

````
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
````

**Comment by franzwilding** [comment]
In order to get AUTHORIZATION header in Symfony? If so, we should add this to the docs. Thank you for investigation!

**Comment by franzwilding** [comment]
@stefan-kamsker Can you check this, as it is a server topic and update docs if needed?

**Comment by NMathar** [comment]
The Symfony Docs have a place for it too https://symfony.com/doc/current/setup/web_server_configuration.html#apache-with-mod-php-php-cgi

**Comment by franzwilding** [comment]
K, then we will just link this docs. Thx

**Comment by stefan-kamsker** [comment]
It's linked in the tutorial
https://medium.com/unite-cms/how-to-setup-unite-cms-for-local-development-or-on-a-production-server-c1da99fa5c90

but not in the docs,

i will improve the docs too!

**Comment by stefan-kamsker** [comment]
updated the docs!
