### ISSUE TITLE
Implement API restore / delete definitely actions

### ISSUE THREAD

**Issue by franzwilding** [unite-cms/unite-cms#4]
Implement graphQL mutations to ~delete~, restore and delete-definitely content. This is already implemented in ContentController and can easily be re-implemented as graphql mutation types.

Consider to refactor the actions by creating some service that takes care of content deletion and will be used in the controller and the mutation.

**Comment by TomDeSmet** [comment]
I see this has been moved to the next milestone multiple times. Any idea if this is going to make the next release? Seems like an important feature for any CMS.

**Comment by stefan-kamsker** [comment]
hi,

currently it's planned for the next release V0.8

you can also upvote the feature here:
https://github.com/unite-cms/unite-cms/issues/351

Best regards!

**Comment by TomDeSmet** [comment]
I know it's possible in the CMS, but I'm testing UniteCMS as a DB/GraphQL server only for an app I'm building. So I won't be using the CMS functionality to edit my content.

**Comment by franzwilding** [comment]
I see. Maybe we can implement at least the delete endpoint earlier. And the revert, delete definitely and recover endpoints later. Would this help you with your app?

**Comment by TomDeSmet** [comment]
Definitely! That would be great.

**Comment by franzwilding** [comment]
We will implement API delete feature in the next release (0.7.3) https://github.com/unite-cms/unite-cms/issues/378. Delete definitely and revert will be delayed for now
