### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by kherox** [unite-cms/unite-cms#400]
I using W10 with Server version: 10.1.36-MariaDB. 
When i run this command : php bin/console doctrine:schema:update --force , i have this : 
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes. 
I try solve this with many method but nothing work.

**Comment by kherox** [comment]
To solve this change conf 
driver: pdo_mysql
        host: '%env(DATABASE_HOST)%'
        port: '%env(DATABASE_PORT)%'
        dbname: '%env(DATABASE_NAME)%'
        user: '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_general_ci
file is located in conf/packages/doctrine.yaml

**Comment by stefan-kamsker** [comment]
Hi,

ok, thanks for the info

i don't know the state of all JSON functions in mariadb, mariadb is often a little bit behind mysql, so you have to test this out.

Best regards!
