### ISSUE TITLE
Hidden Field

### ISSUE THREAD

**Issue by Clonk-HTML5** [unite-cms/unite-cms#407]
Hi,

i have a Project where i need a hidden Field in a Content-Type for saving some Data.
What do you think about such a Field ?

**Comment by stefan-kamsker** [comment]
Hi,

makes absolutely sense for some use cases.
i added it to milestone 0.8

Best regards!

**Comment by Clonk-HTML5** [comment]
not to render the Fields would be a better solution.

**Comment by darends** [comment]
+1 Setting it to not render seems best, so that any benefits from field types can still be gained

**Comment by darends** [comment]
Adding to this, a read-only attribute would add to making this a fully functioning feature

**Comment by joshua-sharp** [comment]
I'm trying to implement the read only and hidden fields. I nearly completed the read only field yesterday, and will finish it off later in the week

**Comment by stefan-kamsker** [comment]
Great,

thank you for contributing to the project, we are really happy!

Best regards!
