### ISSUE TITLE
UI Feature: Group Fields

### ISSUE THREAD

**Issue by Karls-Developers** [unite-cms/unite-cms#419]
Hi,

a cool Feature would a group-function for Fields.
For Example i have an min and an max Number Field these 2 could be grouped in one Row.

![bildschirmfoto 2018-12-13 um 14 29 54](https://user-images.githubusercontent.com/30835517/49941882-05e9b100-fee4-11e8-9e2a-72f72a1e5e16.png)

Thanks

**Comment by stefan-kamsker** [comment]
hi,

yes, would be a nice enhancement

Best regards!

**Comment by darends** [comment]
+1 This looks promising
