### ISSUE TITLE
Checkboxtype returns Type String in Graphql

### ISSUE THREAD

**Issue by Clonk-HTML5** [unite-cms/unite-cms#420]
Hi,

the CheckboxFieldtype returns Type String in Graphql it should be Boolean.

**Comment by stefan-kamsker** [comment]
hi, 

can you please do a new PR for checkboxtype
was reverted together with #422 

thx

**Comment by Clonk-HTML5** [comment]
Hi,

no problem ;-)

**Comment by stefan-kamsker** [comment]
thx, was merged
