### ISSUE TITLE
Numbertype returns Type String in Graphql

### ISSUE THREAD

**Issue by Clonk-HTML5** [unite-cms/unite-cms#422]
Hi,

the NumberFieldtype returns Type String in Graphql it should be Int.

**Comment by stefan-kamsker** [comment]
hi,

i had to revert the PR, number is not always a integer, was too fast :)
can you please fix it?

thx

**Comment by Clonk-HTML5** [comment]
Hi,

thats right a bit to fast ;-)
I did not see the Integer Type.
Number should be Float ;-)

Thanks

**Comment by Clonk-HTML5** [comment]
I added the Int Type to the IntegerfieldType

**Comment by stefan-kamsker** [comment]
thx, i also didn't see it, np :)
