### ISSUE TITLE
UI improvement: Hide Content Actions if user has no permission

### ISSUE THREAD

**Issue by stefan-kamsker** [unite-cms/unite-cms#433]
If I'm only a viewer with no additional permissions, all content actions are visible which lead to a "not allowed" on click.

Interface would be much clearer if not allowed actions are not visible

![bildschirmfoto 2018-12-18 um 13 05 55](https://user-images.githubusercontent.com/34944934/50153126-c8ab6780-02c5-11e9-8e68-e74e1451f718.png)

**Comment by franzwilding** [comment]
Yes, this is exactly the issue I am resolving the moment https://github.com/unite-cms/unite-cms/issues/121

**Comment by stefan-kamsker** [comment]
oh sry, i should check the tickets first :(
