### ISSUE TITLE
Collection Min Row Setting not working

### ISSUE THREAD

**Issue by stefan-kamsker** [unite-cms/unite-cms#438]
```
{
  "title": "Foo",
  "identifier": "foo",
  "type": "collection",
  "settings": {
    "min_rows": 1,
    "fields": [
      {
        "title": "Bar",
        "identifier": "bar",
        "type": "text"
      }
    ]
  }
}
```
I'm expecting that i can't save content without one filled out collection row, but i can.

**Comment by franzwilding** [comment]
Hey!

I think everything is working correctly here. The setting "min_rows" means, that there are at least the number of rows set in min_rows. It does not control if the fields in each row are required or not (which is not possible for the collection field).
