### ISSUE TITLE
Search in Listview

### ISSUE THREAD

**Issue by Benedict-Lojewski** [unite-cms/unite-cms#453]
I have a problem with Unite-CMS search. We have multiple Unite-CMS Servers and on some there is the search bar on top active and on some not. I've updated every server but with no success. I need the search on all the tools but i can't figure out why it's running on some servers but not on all.

Below I show you two separate server views:

#### with search (Table View)
![bildschirmfoto 2019-01-07 um 13 42 32](https://user-images.githubusercontent.com/44462588/50768886-66210800-1282-11e9-89fb-6c4b0b2776cd.png)

#### without search (Table View)
![bildschirmfoto 2019-01-07 um 13 42 39](https://user-images.githubusercontent.com/44462588/50768887-66210800-1282-11e9-8965-ba8a877b815e.png)

Any ideas whats wrong? Do I forgot to add a setting anywhere?

**Comment by franzwilding** [comment]
Hey! At the moment the search bar is only visible for views where drag-drop sorting is not enabled. We could think about a solution, where we show the searchbar all of the time but disable the drag-drop feature during searching.

**Comment by Benedict-Lojewski** [comment]
Thank you! It worked.

Yeah the solution sounds great. Search needs to be enabled all the time, it makes things alot easier.

**Comment by franzwilding** [comment]
In 0.11 we will bring back search feature to views again!
