### ISSUE TITLE
Search paging

### ISSUE THREAD

**Issue by Benedict-Lojewski** [unite-cms/unite-cms#455]
I found a bug with the search function. When you go without searching to the last page or one page that is furtherer away from page 1 and now start searching, it seams not to search anything. But it's searching something and you land on a blank page (see image below). When you now change the page, you got all results.

![bildschirmfoto 2019-01-08 um 08 37 18](https://user-images.githubusercontent.com/44462588/50816454-f1e97180-1320-11e9-887f-61b0042ccd60.png)

**Comment by franzwilding** [comment]
Nice found! Will be fixed.

**Comment by franzwilding** [comment]
fixed by https://github.com/unite-cms/unite-cms/pull/466
