### ISSUE TITLE
Support custom fields (missing location fields)

### ISSUE THREAD

**Issue by regnerisch** [unite-cms/unite-cms#456]
I'm missing support for location fields. So it would be nice to add them, especially it would be awesome to add support for custom fields. So you can easily add your own custom code for rendering fields, something like: 

```json
{
  //..., 
  "fields": [
    {
      //...,
      "type": "custom",
      "settings": {
        "render": "../path/to/field.vue",
        "values": [
          "latitude", "longitude" // Values which are saved in DB (should most of the time only be one value)
        ],
        "variables": { // additional Variables which are passed to the vue script 
          "api_key": "ABC",
          "another_custom_variable": "123"
        }
      }
    }
  ]
}
```

**Comment by franzwilding** [comment]
Hey!

Yes, the idea of custom fields is great. However I would only allow absolute urls to web component includes together with predefined component names. Something like this: 

```
{
    "settings" : {
        "webcomponent": "https://mycomponents.example.com/field_component.js"
    }
}

This would work for views as well. 

Unfortunately I think that we have to implement more important features before, so it will take some time. 

In the meantime, if you are hosting unite cms by your own, you can also easily register new field types.

**Comment by franzwilding** [comment]
By the way: We now have a very basic location field you can check out

**Comment by franzwilding** [comment]
With version 0.10 you can easily add custom fields, by writing some php and vue.js code. In the future we are also planing to support external hosted components to render the field. 

The next weeks, we will provide docs for the new version.
