### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by huiyang** [unite-cms/unite-cms#465]
I followed the instruction in the document to install the unite cms, i have created the admin user account and the organization using the console command as in the document as well, then i login with the username and password i used to create the admin account, no any error display, but it keep go back to the login page. I tried to change the url to http://localhost/unitecms/public also but no luck.

I tried to debug in symfony 
AuthenticationProviderManager class,

and confirmed that the statement:
$this->eventDispatcher->dispatch(AuthenticationEvents::AUTHENTICATION_SUCCESS, new AuthenticationEvent($result));

is executed. which mean the username and password is correct.
But still, it always go to the login page no matter what i tried.

I am using unitecms v0.7.6 and symfony v4.1.8, PHP 7.2.12

**Comment by stefan-kamsker** [comment]
Hi,

another user had the similar issue already

maybe that does help, see https://github.com/unite-cms/unite-cms/issues/393

also check if the cookies are set correctly, maybe there are problems if you use localhost.

Best regards!

**Comment by huiyang** [comment]
Hi, thanks for your reply.

#393 was solved after update to the latest version, but i am using the latest version.
You mean the cookies setting of unitecms or browser?

I can login to any other localhost website without issue so i guess the cookie setting of my browser don't have any issue. If you are referring the unitecms cookie setting, how to set it?

Thanks.

**Comment by stefan-kamsker** [comment]
Hi,

You mean the cookies setting of unitecms or browser?
yes, maybe there's something

what did you set for the following ENV variables in .env file
ROUTING_APPROACH
DEFAULT_HOSTNAME

Then i will try to reproduce it!

Thx

Best regards!
Stefan

**Comment by huiyang** [comment]
I tried in google chrome incognito mode as well, still exactly the same.

Here is my the .env file content

APP_ENV=dev
ROUTING_APPROACH=parameter
DEFAULT_HOSTNAME=localhost/unitecms/public
APP_SECRET=SECRET
DATABASE_HOST=127.0.0.1
DATABASE_PORT=
DATABASE_NAME=unite
DATABASE_USER=root
DATABASE_PASSWORD=root
MAILER_SENDER=test@example.com
MAILER_URL=smtp.gmail.com

Thanks.

**Comment by stefan-kamsker** [comment]
Hi,

tried tp reproduce this setup.

ROUTING_APPROACH=parameter
DEFAULT_HOSTNAME=localhost
with apache pack or a .htaccess file in public folder https://gist.github.com/Guibzs/a3e0b3ea4eb00c246cda66994defd8a4 is working for me

Anyway, i really don't recommend you such a setup.

Configure a apache vhost or nginx for unite cms.
https://symfony.com/doc/current/setup/web_server_configuration.html

and use a local test domain fe. /etc/hosts on osx or linux, Windows\System32\drivers\etc\hosts on Windows
127.0.0.1     unite.test

Best Regards!
Stefan
