### ISSUE TITLE
Setting Types: translations does not consist all the elements.

### ISSUE THREAD

**Issue by rameshlohala** [unite-cms/unite-cms#484]
when querying setting, it always assumes 1 locale as default and in the translations array it excludes data for that default locale. The api should return all translations. and also the setting query should accept locale argument in order to return the fields as translated data according to the locale. 

approached query(assuming there are 2 locales ["en", "fr"])
```
{
  Setting(locale: en) {
    locale
    title
    content
    translations (locales: null) {
      locale
      title
      content
    }
  }
}
```

expected result:

```
{
  "data": {
    "Setting": {
      "locale": "en",
      "title": "title-en",
      "content": "content-en",
      "translations": [
        {
          "locale": "en",
          "title": "title",
          "content": "content"
        },
        {
          "locale": "fr",
          "title": "title-fr",
          "content": "content-fr"
        }
      ]
    }
  }
}
```

**Comment by stefan-kamsker** [comment]
Hi,

thank you, we will have a look

best regards!
