### ISSUE TITLE
Feature request backend listings 'Add filter' feauture

### ISSUE THREAD

**Issue by mmf-amarcos** [unite-cms/unite-cms#486]
It would be great to have filter funcionality on the list templates. Something like, for example, the Add Filter link in https://marmelab.com/react-admin-demo/#/customers

On Gitter Franz Wilding answered:

For the sake of simplicity, at the moment the search filter will be transformed to an OR-Query that looks something like this:
``` sql
 WHERE field1 LIKE "%value%" OR field2 LIKE "%value%" OR field3 LIKE "%value%" ...
```
So having a composable AND /OR filter widget is not very hard to implement. It can be done almost complete in the vue.js component.

**Comment by franzwilding** [comment]
We totally need this! For version 0.10 I am planing to work on the Content view component (also things like batch delete etc.) and also on this filter feature

**Comment by franzwilding** [comment]
0.10 turned out into a complete rewrite, we are planing this feature for version 0.11
