### ISSUE TITLE
Adding Validation definition to a ContentType fails

### ISSUE THREAD

**Issue by darends** [unite-cms/unite-cms#490]
I am trying to add validation to a Content Type.
I'm using the newest docker image for testing.

When adding validation to a domain get this error.
```
contentTypes[product].validations[0][expression]: Invalid validations definition. Validations must be set as array of validation objects.
```
Below is my domain's config
```
{
  "title": "Store",
  "identifier": "store",
  "content_types": [
    {
      "title": "Product",
      "identifier": "product",
      "content_label": "{type} #{id}",
      "fields": [
        {
          "title": "Firstname",
          "identifier": "firstname",
          "type": "text"
        }
      ],
      "views": [
        {
          "title": "All",
          "identifier": "all",
          "type": "table"
        }
      ],
      "permissions": {
        "view content": "true",
        "list content": "true",
        "create content": "member.type == \"editor\"",
        "update content": "member.type == \"editor\"",
        "delete content": "member.type == \"editor\""
      },
      "validations": [
        {
          "expression": "data.firstname != ''",
          "message": "This field firstname is required.",
          "path": "firstname",
          "groups": [
            "CREATE"
          ]
        }
      ]
    }
  ],
  "setting_types": [],
  "domain_member_types": [
    {
      "title": "Editor",
      "identifier": "editor",
      "domain_member_label": "{accessor}",
      "fields": []
    },
    {
      "title": "Viewer",
      "identifier": "viewer",
      "domain_member_label": "{accessor}",
      "fields": []
    }
  ],
  "permissions": {
    "view domain": "true",
    "update domain": "false"
  }
}
```

I used the example of the `validations` snippet from the UniteCMS docs.

I'm not sure why this config should fail when using an example from the docs

Thanks

**Comment by franzwilding** [comment]
Hex @darends!

Yesterday we released version 0.8 of unite cms where the different expression language functions and objects where finally normalized. 

Now you can access the fields of the content type object via `content.data.firstname` instead of data.firstname. And this works for validation and permission expressions the same way. 

Please re-open, if there are any further questions / problems.

**Comment by darends** [comment]
Ahh Thanks @franzwilding !

I realise docs arent the easiest of things to keep up-to-date, so thank you for the quick reply and assistance.
Using `content.data.firstname` does allow validation to pass.

I have also managed to get `content_unique` to work, It might be nice to see mention of this great feature in the docs, as i had to scour the code to find it's reference.

Thanks again

**Comment by franzwilding** [comment]
You are right! This is a new feature and at the moment are are using unite cms in so many projects, that we had no time to update the docs (shame on us). Will be fixed soon!
