### ISSUE TITLE
Standardise description attribute location

### ISSUE THREAD

**Issue by darends** [unite-cms/unite-cms#494]
I noticed that the `description` attribute is defined in two places.

For Variants, the `description` is located `settings.variants[].description`
```json
{
  "title": "Name",
  "identifier": "name",
  "type": "variants",
  "settings": {
    "variants": [
      {
        "title": "Company",
        "identifier": "company",
        "description": "This is a company"
      }
    ]
  }
}
```

However in for all other fields the `description` is located `settings.description`
> **Common settings**
> All field types allow to define at least the optional "description" setting which is just a text and will be rendered below the field.

Should the `description` for Variants be located `settings.variants[].settings.description`
Leaving below as top level items
* `title`
* `identifier`
* `type`
* `settings`

This is just something I noticed and wanted to see your thoughts on this

**Comment by franzwilding** [comment]
I like the idea, it would make things more easy. Since this is a breaking change, we can work on this feature but can only release it in 0.9
