### ISSUE TITLE
Deeply nested Collection not rendering

### ISSUE THREAD

**Issue by darends** [unite-cms/unite-cms#496]
I am setting up a deeply nested set of fields

```
variants [A]
    collection [B]
        variants [C]
            reference[D]
```

`variant [A]` renders correctly and allows the selection of the chosen variant.
After selecting a variant, the resultant `collection [B]` block does not display at all.
Any other Collection within this content type also does not render.
^1 see first file in gist for content_type definition

Content of the gists
1. `variant [A]`      -only first gist has children
    1. `collection [B]`
        1. `variants [C]`
            1. `reference[D]`
2. `collection [B]`  -- to show that individual configuration snippets are valid
    1. `variants [C]`
          1. `reference[D]`
3. `collection [B]` -- to show that individual configuration snippets are valid
4. `variants [C]`   -- to show that individual configuration snippets are valid
      1. `reference[D]`

^1 => https://gist.github.com/darends/d2ddc2bb732742795b71788590dd560c

If you have further clarifications to make i am hoping to work with you guys on this

-Dirk

**Comment by franzwilding** [comment]
Hm, There is definitiv a problem with the variants field. I would be very happy, if you find the reason for this bug or have a hint, when this problem occurs and when not.

**Comment by franzwilding** [comment]
Hey @darends !

Looks like, we just forgot to dump field assets when variant fields are rendered. This leads to the following problem: 

If the first occurrence of a field type (for example collection) is inside a variants field, the js and css assets of this field will never be loaded. I just created a PR with a one-liner fix. Please re-open this issue, if you still have problems.
