### ISSUE TITLE
Search is case sensitive

### ISSUE THREAD

**Issue by darends** [unite-cms/unite-cms#498]
Unite CMS' UI performs searches using the graphQL API

While the API may be reasonable to be case sensitive.
The UI should be case insensitive.

Maybe a variable is added to the graphQL query to enable case insensitivity.

At some point it would be really fancy to have fuzzy searching,
but I understand that would be unreasonable in the short term

-Dirk

**Comment by franzwilding** [comment]
I think it should not be that hard. We are doing a SQL `LIKE` check when searching and could very easily use the `LOWER()` function for value comparison.

**Comment by franzwilding** [comment]
Fixed by https://github.com/unite-cms/unite-cms/pull/521
