### ISSUE TITLE
View definition for fields using Full Field Configuration 

### ISSUE THREAD

**Issue by darends** [unite-cms/unite-cms#500]
Configuring fields of a view using the Full Field Configuration style returns an error

`contentTypes[product].views[coming].settings: Unknown field "0"`

```json
{
    "title": "Coming Soon",
    "identifier": "coming",
    "type": "table",
    "icon": "filter",
    "settings": {
        "sort": {
            "field": "created",
            "asc": false,
            "sortable": false
        },
        "fields": [
            {
                "title": "Name",
                "identifier": "name",
                "type": "text"
            }
        ],
        "filter": {
            "field": "state",
            "operator": "=",
            "value": "coming"
        }
    }
}
```

The other configuration styles `Only Identifiers` & `Fields And Headlines` work as expected

I really want to try out this feature but am currently unable to.

-Dirk

**Comment by franzwilding** [comment]
Hey!

The full field configuration must have the field identifier as object keys: 

```
"fields": {
        "icon": { "label": "Icon", "type": "text", "settings": [] },
        "content": { "label": "Content", "type": "wysiwyg" }
      }
```

I think we docs are not very easy to read here. We should improve it!
