### ISSUE TITLE
Add a Create Entry button in the list of content types

### ISSUE THREAD

**Issue by darends** [unite-cms/unite-cms#501]
A nice convenience would be to display a Create Entry button in the list of Content Types

![products - unite cms 1](https://user-images.githubusercontent.com/45986151/52091415-7b325200-2608-11e9-9371-5ab0ef64dd08.png)

-Dirk

**Comment by franzwilding** [comment]
Good idea!
Shouldn't be that hard to implement. We only need to check if the user is allowed to create a new content. 

Maybe the "+" icon should only be visible on hover and there should be a title and uk-tooltip attribute.

Do you want to create a PR for this?
