### ISSUE TITLE
content_label not resolving

### ISSUE THREAD

**Issue by darends** [unite-cms/unite-cms#503]
As seen at https://www.unitecms.io/recipes.html in the simple blog example,
the `articles` content type uses `content_label`

I have not been able to replicate the functionality with the same or a different field.

```json
{
    "title": "Simple Blog",
    "identifier": "simple_blog",
    "content_types": [
        {
            "title": "Articles",
            "identifier": "articles",
            "content_label": "{headline}",
            "fields": [
            ]
        }
    ]
}
```
![update _top navigation 0a816477-25b3-11e9-bd39-0a580a800047_ - unite cms](https://user-images.githubusercontent.com/45986151/52097576-b4c28780-261f-11e9-99ce-8a0f7ea88db4.png)

-Dirk

**Comment by franzwilding** [comment]
Hey @darends!

The content label is used in two places:
- Headline of the delete / update pages of a content element
- For rendering a referenced content element

In your example you would need to have a content_label for the content type product and a field "name" on the content type product. 

Can you show your product content type?

**Comment by darends** [comment]
I have not been able to replicate the issue after the weekend.

This is the product content type (with extra fields omitted)
```json
{
    "title": "Products",
    "identifier": "product",
    "content_label": "{name}",
    "icon": "gift",
    "fields": [
        {
            "identifier": "name",
            "title": "Name",
            "type": "text",
            "settings": {
                "description": "Description of Product. This will be shown on a product's page",
                "not_empty": true
            }
        }
    ]
}
```

I feel it may have been cached somewhere but it is fixed now
