### ISSUE TITLE
ext_log_entries

### ISSUE THREAD

**Issue by crmn-frws** [unite-cms/unite-cms#523]
the user-email is added in column username for log entries in ext_log_entries. wouldn't it be better to log the user identifier (because it's possible to change username/usermail)? by the way, changing email is not logged there...

**Comment by franzwilding** [comment]
Thank you for the issue! At user identifier in the log should only show the actor who performed the action. This should also be available, even if the user was deleted. 

Maybe we should add an additional reference to the user in the future.

**Comment by franzwilding** [comment]
moved to 0.9, because this needs a DB update.
