### ISSUE TITLE
Can´t select item after switching between Active and Deleted

### ISSUE THREAD

**Issue by uldo** [unite-cms/unite-cms#549]
selectrow control disappears after switching between active and deleted (back to active) content

![select reference bug](https://user-images.githubusercontent.com/6816730/55247266-6e685e00-5247-11e9-836a-cfb56aceb75d.gif)

**Comment by franzwilding** [comment]
Thank you for the report. Will be fixed in the next release, 0.8.1. is already closed now

**Comment by franzwilding** [comment]
Maybe a duplicate of https://github.com/unite-cms/unite-cms/pull/514. I will try if version 0.8.1 (just released) already solved this issue.

**Comment by franzwilding** [comment]
Yes, this was fixed in #514. Thank you for reporting anyway!
