### ISSUE TITLE
Generated assets in version control

### ISSUE THREAD

**Issue by pspiller** [unite-cms/unite-cms#609]
Several Webpack-generated files are currently under version control: JS and CSS files, `entrypoints.json`, `manifest.json`, etc. These files need to be regenerated frequently during development, which causes cluttered Git output when old files are removed and new ones created.

I'm guessing the generated files are under version control so the application is ready to run after the repository is cloned. This does make it easier to try out, rather than having to run additional commands to compile the assets.

Instead, can I suggest using GitHub's releases feature with attached archives containing the code and generated files? The generated files could then be removed from version control. People who want to try out Unite could download and extract the archive.

I realise this approach would involve more work than just committing the generated files, as you'd need to build the release archives. But it would be easier for anyone developing the application as opposed to users looking only to install, who might find it easier to use the GitHub releases feature anyway.

**Comment by franzwilding** [comment]
I know it is not ideal, however, the recommended way to run unite cms is to use Composer. So the GitHub archive feature will not work here.

However, these files are only under version control for the core bundles. If you have an own instance of unite cms, any new assets you want to have there will be built into /public and you can decide (.gitignore) to include them or not.

**Comment by pspiller** [comment]
If the idea is that people can install the application using Composer and then immediately run it without needing to generate assets, then I agree you'd need to include the pre-generated assets in version control.

If generated assets weren't stored in version control, GitHub's releases feature could be used alongside Composer to still allow easy installation:

- Users that want to try out unite cms could download and extract the release archive (containing pre-generated assets), run `composer install` and then proceed with setup.

- Developers that want to work on unite cms could install via Composer (or clone the repository), generate the assets and then proceed with setup.

My organisation does keep customisations in a separate bundle where possible, where we ignore and don't commit generated assets. When working on changes to core unite cms code, though, having generated assets in version control makes it harder to view changes and history.

We can work around the issue and I understand if the trade-offs aren't worth it. Just wanted to suggest it as a potential improvement.

**Comment by franzwilding** [comment]
Closed for the moment, we can think about this after version 1.0
