### ISSUE TITLE
CKEditor link input element not displaying correctly

### ISSUE THREAD

**Issue by pspiller** [unite-cms/unite-cms#618]
From version 0.8.1 onward, the link input element for CKEditor-powered WYSIWYG fields doesn't display properly. In 0.8.0, if you highlight some text and click the 'Link' button (or hit ctrl-k), an input element appears to allow you to enter or edit a URL:

![ckeditor_link_input](https://user-images.githubusercontent.com/1845477/58232258-7393e600-7d7c-11e9-9162-ae43f6f0edea.png)

In 0.8.1, the input element doesn't display correctly. It appears stretched out at the bottom of the page (in Firefox) or isn't obviously visible at all (in Chrome). This appears to be due to some CKEditor reset CSS being included twice: once with the lowest priority (correct) and a second time with a higher priority (causing the issue):

![ckeditor_failing_link_input_styles](https://user-images.githubusercontent.com/1845477/58232261-78589a00-7d7c-11e9-9dfd-a17bdd62f521.png)

Disabling the higher-priority set of reset rules using browser debug tools fixes the issue in Chrome and Firefox. The issue appears to have been introduced in commit f1b3feb9.

**Comment by franzwilding** [comment]
@pspiller thank you!
