### ISSUE TITLE
domain reference problem

### ISSUE THREAD

**Issue by MelanieJakob** [unite-cms/unite-cms#628]
I added {
                    "title": "Channel",
                    "identifier": "channel",
                    "type": "reference",
                    "settings": {
                        "domain": "portal",
                        "content_type": "channel",
                        "view": "all",
                        "content_label": "{name}"
                    }
                }
in the domain topics. When I call the api to get topics with the associated channel I get this
Error message "A reference field was configured with domain \"portal\". However you are not allowed to access it."

**Comment by franzwilding** [comment]
Hey! Your Api key must be a member of both domains and must have Content LIST and VIEW permissions on the portal CT.

**Comment by MelanieJakob** [comment]
The Api key is a member of both domains and the permissions are true on the portal CT for List and View.

**Comment by franzwilding** [comment]
Hmm. Which version of unite cms are you using?

**Comment by MelanieJakob** [comment]
Version 0.8.1

**Comment by franzwilding** [comment]
Hm... This is strange.

You can try to update to dev-master (which will soon be released under 0.9), however there are some deeper changes between 0.8.1 and 0.9. 

You can also try to debug inside the DomainVoter and see, why you are not allowed to access the domain

**Comment by franzwilding** [comment]
Also if you send me the two domain configuration (including CT) I can check out this bug next week

**Comment by MelanieJakob** [comment]
the two domain configuration: 
<pre>
{
  "title": "Portale",
  "identifier": "portal",
  "content_types": [
    {
      "title": "Channel",
      "identifier": "channel",
      "content_label": "{name}",
      "fields": [
        {
          "title": "Name",
          "identifier": "name",
          "type": "text"
        },
        {
          "title": "Beschreibung",
          "identifier": "description",
          "type": "textarea"
        }
      ],
      "views": [
        {
          "title": "All",
          "identifier": "all",
          "type": "table"
        }
      ],
      "permissions": {
        "view content": "true",
        "list content": "true",
        "create content": "member.type == \"editor\"",
        "update content": "member.type == \"editor\"",
        "delete content": "member.type == \"editor\""
      }
    }
  ],
  "domain_member_types": [
    {
      "title": "Editor",
      "identifier": "editor",
      "domain_member_label": "{accessor}",
      "fields": []
    },
    {
      "title": "Viewer",
      "identifier": "viewer",
      "domain_member_label": "{accessor}",
      "fields": []
    }
  ],
  "permissions": {
    "view domain": "true",
    "update domain": "true"
  }
}
</pre>

<pre>
{
    "title": "Themen",
    "identifier": "topics",
    "permissions": {
        "view domain": "true",
        "update domain": "true"
    },
    "domain_member_types": [
        {
            "title": "Editor",
            "identifier": "editor",
            "domain_member_label": "{accessor}",
            "fields": []
        },
        {
            "title": "Viewer",
            "identifier": "viewer",
            "domain_member_label": "{accessor}",
            "fields": []
        }
    ],
    "content_types": [
        {
            "title": "Manufakturen",
            "identifier": "factories",
            "content_label": "{headline} - {priority}",
            "fields": [
                {
                    "title": "Slug",
                    "identifier": "slug",
                    "type": "slug",
                    "settings": {
                        "source": "headline"
                    }
                },
                {
                    "title": "Standorte",
                    "identifier": "locations",
                    "type": "collection",
                    "settings": {
                        "min_rows": "1",
                        "max_rows": "10",
                        "fields": [
                            {
                                "title": "Standort",
                                "identifier": "location",
                                "type": "reference",
                                "settings": {
                                    "domain": "topics",
                                    "content_type": "locations",
                                    "view": "all",
                                    "content_label": "{name}"
                                }
                            }
                        ]
                    }
                },
                {
                    "title": "Priorit\u00e4t",
                    "identifier": "priority",
                    "type": "choice",
                    "settings": {
                        "choices": "@prioritys"
                    }
                },
                {
                    "title": "Tags (Kommasepariert)",
                    "identifier": "tags",
                    "type": "text"
                },
                {
                    "title": "\u00dcberschrift",
                    "identifier": "headline",
                    "type": "text"
                },
                {
                  "title": "Untertitel",
                  "identifier": "subtitle",
                  "type": "collection",
                  "settings": {
                    "min_rows": "0",
                    "max_rows": "1",
                    "fields": [
                      {
                        "title": "\u00dcberschrift",
                        "identifier": "headline",
                        "type": "text"
                      },
                      {
                        "title": "Text",
                        "identifier": "text",
                        "type": "textarea",
                        "settings": "@textarea_settings"
                      }
                    ]
                  }
                },
                {
                    "title": "Beschreibung",
                    "identifier": "description",
                    "type": "textarea",
                    "settings": "@textarea_settings"
                },
                {
                    "title": "Bilder ",
                    "identifier": "images",
                    "type": "collection",
                    "settings": {
                        "fields": [
                            {
                                "title": "Bild",
                                "identifier": "image_collection",
                                "type": "mediaimage",
                                "settings": {
                                    "bucket": "@bucketImage"
                                }
                            }
                        ]
                    }
                },
                {
                    "title": "Video",
                    "identifier": "video",
                    "type": "media",
                    "settings": {
                        "bucket": "@bucketVideo"
                    }
                },
                {
                    "title": "Als Neu markieren ab",
                    "identifier": "mark_as_new",
                    "type": "datetime"
                },
                {
                    "title": "Startdatum",
                    "identifier": "start_date",
                    "type": "datetime"
                },
                {
                    "title": "Enddatum",
                    "identifier": "end_date",
                    "type": "datetime"
                },
                {
                    "title": "Inhalte",
                    "identifier": "content",
                    "type": "collection",
                    "settings": {
                        "min_rows": "0",
                        "max_rows": "99",
                        "fields": [
                            {
                                "title": "Inhaltstypen",
                                "identifier": "content_types",
                                "type": "variants",
                                "settings": {
                                    "variants": [
                                        {
                                            "title": "Text",
                                            "identifier": "text",
                                            "description": "Ein normaler Text",
                                            "icon": "file-text",
                                            "fields": [
                                                {
                                                    "title": "\u00dcberschrift",
                                                    "identifier": "headline",
                                                    "type": "text"
                                                },
                                                {
                                                    "title": "Text",
                                                    "identifier": "text",
                                                    "type": "textarea",
                                                    "settings": "@textarea_settings"
                                                }
                                            ]
                                        },
                                        {
                                            "title": "Listen",
                                            "identifier": "lists",
                                            "description": "Listen",
                                            "icon": "list",
                                            "fields": [
                                                {
                                                    "title": "Listen \u00dcberschrift",
                                                    "identifier": "headline",
                                                    "type": "text"
                                                },
                                                {
                                                    "title": "Liste",
                                                    "identifier": "list",
                                                    "type": "collection",
                                                    "settings": {
                                                        "fields": [
                                                            {
                                                                "title": "\u00dcberschrift",
                                                                "identifier": "headline",
                                                                "type": "text"
                                                            },
                                                            {
                                                                "title": "Listen Texte",
                                                                "identifier": "list_texts",
                                                                "type": "collection",
                                                                "settings": {
                                                                    "fields": [
                                                                        {
                                                                            "title": "Text",
                                                                            "identifier": "text",
                                                                            "type": "textarea",
                                                                            "settings": "@textarea_settings"
                                                                        }
                                                                    ]
                                                                }
                                                            }
                                                        ]
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            "title": "Bild und Text",
                                            "identifier": "image_and_text",
                                            "description": "Bild und Text",
                                            "icon": "image",
                                            "fields": [
                                                {
                                                    "title": "\u00dcberschrift",
                                                    "identifier": "headline",
                                                    "type": "text"
                                                },
                                                {
                                                    "title": "Text",
                                                    "identifier": "text",
                                                    "type": "textarea",
                                                    "settings": "@textarea_settings"
                                                },
                                                {
                                                    "title": "Bild",
                                                    "identifier": "image",
                                                    "type": "mediaimage",
                                                    "settings": {
                                                        "bucket": "@bucketImage"
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            "title": "Video",
                                            "identifier": "video",
                                            "description": "Eine Video-Datei",
                                            "icon": "video",
                                            "fields": [
                                                {
                                                    "title": "Video",
                                                    "identifier": "video_file",
                                                    "type": "media",
                                                    "settings": {
                                                        "bucket": "@bucketVideo"
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            "title": "Bilder",
                                            "identifier": "images_wrapper",
                                            "description": "Eine Bilder-Sammlung",
                                            "icon": "image",
                                            "fields": [
                                                {
                                                    "title": "Bilder ",
                                                    "identifier": "images",
                                                    "type": "collection",
                                                    "settings": {
                                                        "fields": [
                                                            {
                                                                "title": "Bild",
                                                                "identifier": "image_collection",
                                                                "type": "mediaimage",
                                                                "settings": {
                                                                    "bucket": "@bucketImage"
                                                                }
                                                            }
                                                        ]
                                                    }
                                                }
                                            ]
                                        },
                                      {
                                        "title": "3D Bilder",
                                        "identifier": "third_dimension_images_wrapper",
                                        "description": "Eine 3D Bilder-Sammlung",
                                        "icon": "image",
                                        "fields": [
                                          {
                                            "title": "3D Bilder ",
                                            "identifier": "images",
                                            "type": "collection",
                                            "settings": {
                                              "fields": [
                                                {
                                                  "title": "Vordergrundbild",
                                                  "identifier": "foreground_image_collection",
                                                  "type": "mediaimage",
                                                  "settings": {
                                                    "bucket": "@bucketImage"
                                                  }
                                                },
                                                {
                                                  "title": "Hintergrundbild",
                                                  "identifier": "background_image_collection",
                                                  "type": "mediaimage",
                                                  "settings": {
                                                    "bucket": "@bucketImage"
                                                  }
                                                }
                                              ]
                                            }
                                          }
                                        ]
                                      },
                                        {
                                            "title": "360° Panoramen",
                                            "identifier": "panoramas_wrapper",
                                            "description": "Eine 360° Panoramen-Sammlung",
                                            "icon": "image",
                                            "fields": [
                                                {
                                                    "title": "360° Panoramen",
                                                    "identifier": "images",
                                                    "type": "collection",
                                                    "settings": {
                                                        "fields": [
                                                            {
                                                                "title": "Bild",
                                                                "identifier": "image_collection",
                                                                "type": "mediaimage",
                                                                "settings": {
                                                                    "bucket": "@bucketImage"
                                                                }
                                                            },
                                                            {
                                                                "title": "URL",
                                                                "identifier": "url",
                                                                "type": "link",
                                                                "settings": {
                                                                    "title_widget": false,
                                                                    "target_widget": true
                                                                }
                                                            }
                                                        ]
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                },
                {
                    "title": "Tagesh\u00f6hepunkte",
                    "identifier": "day_highlights",
                    "type": "collection",
                    "settings": {
                        "min_rows": "0",
                        "max_rows": "99",
                        "fields": [
                            {
                                "title": "Standort",
                                "identifier": "location",
                                "type": "reference",
                                "settings": {
                                    "domain": "topics",
                                    "content_type": "locations",
                                    "view": "all",
                                    "content_label": "{name}"
                                }
                            },
                            {
                                "title": "\u00dcberschrift",
                                "identifier": "headline",
                                "type": "text"
                            },
                            {
                                "title": "Text",
                                "identifier": "text",
                                "type": "textarea",
                                "settings": "@textarea_settings"
                            },
                            {
                                "title": "Bild",
                                "identifier": "image",
                                "type": "mediaimage",
                                "settings": {
                                    "bucket": "@bucketImage"
                                }
                            },
                            {
                                "type": "datetime",
                                "identifier": "start_date",
                                "title": "Startdatum"
                            },
                            {
                                "type": "datetime",
                                "identifier": "end_date",
                                "title": "Enddatum"
                            },
                            {
                                "title": "Wiederholung",
                                "identifier": "repeat",
                                "type": "choice",
                                "settings": {
                                    "choices": {
                                        "T\u00e4glich": 1,
                                        "W\u00f6chentlich": 2,
                                        "Einmalig": 3,
                                        "Wochentags": 4,
                                        "Wochenende": 5,
                                        "Manuell": 6
                                    }
                                }
                            },
                            {
                                "title": "Wochentage",
                                "identifier": "weekdays",
                                "type": "choices",
                                "settings": {
                                    "choices": {
                                        "Montag": 1,
                                        "Dienstag": 2,
                                        "Mittwoch": 3,
                                        "Donnerstag": 4,
                                        "Freitag": 5,
                                        "Samstag": 6,
                                        "Sonntag": 7
                                    }
                                }
                            }
                        ]
                    }
                },
                {
                    "title": "\u00d6ffnungszeiten",
                    "identifier": "opening_hours",
                    "type": "collection",
                    "settings": {
                        "min_rows": "0",
                        "max_rows": "99",
                        "fields": [
                            {
                                "title": "Standort",
                                "identifier": "location",
                                "type": "reference",
                                "settings": {
                                    "domain": "topics",
                                    "content_type": "locations",
                                    "view": "all",
                                    "content_label": "{name}"
                                }
                            },
                            {
                                "title": "\u00dcberschrift",
                                "identifier": "headline",
                                "type": "text"
                            },
                            {
                                "title": "Text",
                                "identifier": "text",
                                "type": "textarea",
                                "settings": "@textarea_settings"
                            },
                            {
                                "type": "datetime",
                                "identifier": "start_date",
                                "title": "Startdatum"
                            },
                            {
                                "type": "datetime",
                                "identifier": "end_date",
                                "title": "Enddatum"
                            },
                            {
                                "title": "Wiederholung",
                                "identifier": "repeat",
                                "type": "choice",
                                "settings": {
                                    "choices": {
                                        "T\u00e4glich": 1,
                                        "W\u00f6chentlich": 2,
                                        "Einmalig": 3,
                                        "Wochentags": 4,
                                        "Wochenende": 5,
                                        "Manuell": 6
                                    }
                                }
                            },
                            {
                                "title": "Wochentage",
                                "identifier": "weekdays",
                                "type": "choices",
                                "settings": {
                                    "choices": {
                                        "Montag": 1,
                                        "Dienstag": 2,
                                        "Mittwoch": 3,
                                        "Donnerstag": 4,
                                        "Freitag": 5,
                                        "Samstag": 6,
                                        "Sonntag": 7
                                    }
                                }
                            }
                        ]
                    }
                },
                {
                    "title": "Preise pro Standort",
                    "identifier": "price_per_location",
                    "type": "collection",
                    "settings": {
                        "fields": [
                            {
                                "title": "Standort",
                                "identifier": "location",
                                "type": "reference",
                                "settings": {
                                    "domain": "topics",
                                    "content_type": "locations",
                                    "view": "all",
                                    "content_label": "{name}"
                                }
                            },
                            {
                                "title": "Preise",
                                "identifier": "prices",
                                "type": "collection",
                                "settings": {
                                    "fields": [
                                        {
                                            "title": "Preistext",
                                            "identifier": "pricetext",
                                            "type": "text"
                                        },
                                        {
                                            "title": "Preis",
                                            "identifier": "price",
                                            "type": "text"
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                },
                {
                    "title": "Links",
                    "identifier": "links",
                    "type": "collection",
                    "settings": "@linkFields"
                },
                {
                    "title": "Downloads",
                    "identifier": "downloads",
                    "type": "collection",
                    "settings": {
                        "fields": [
                            {
                                "title": "Datei",
                                "identifier": "download",
                                "type": "media",
                                "settings": {
                                    "bucket": "@bucketDownloads"
                                }
                            }
                        ]
                    }
                },
                {
                    "title": "Logo",
                    "identifier": "logo",
                    "type": "collection",
                    "settings": {
                        "fields": [
                            {
                                "title": "Bild",
                                "identifier": "image_collection",
                                "type": "mediaimage",
                                "settings": {
                                    "bucket": "@bucketImage"
                                }
                            }
                        ]
                    }
                },
                {
                    "title": "Fußnote",
                    "identifier": "footnote",
                    "type": "collection",
                    "settings": {
                        "fields": [
                            {
                                "title": "Text",
                                "identifier": "text",
                                "type": "textarea",
                                "settings": "@textarea_settings"
                            }
                        ]
                    }
                },
                {
                    "title": "Channel",
                    "identifier": "channel",
                    "type": "reference",
                    "settings": {
                        "domain": "portal",
                        "content_type": "channel",
                        "view": "all",
                        "content_label": "{name}"
                    }
                }
            ],
            "views": [
                {
                    "title": "All",
                    "identifier": "all",
                    "type": "table",
                    "settings": {
                        "fields": {
                            "headline": "\u00dcberschrift",
                            "locations": {
                              "label": "Standort",
                              "settings": {
                                "fields": {
                                  "location": {
                                    "settings": { "fields": ["name"] }
                                  }
                                }
                              }
                            },
                            "created": "Erstellt am",
                            "mark_as_new": "Als Neu markieren ab",
                            "start_date": "Startdatum",
                            "end_date": "Enddatum"
                        },
                        "filter": {
                            "field": "locale",
                            "operator": "=",
                            "value": "@default_local"
                        }
                    }
                }
            ],
            "permissions": {
                "view content": "true",
                "list content": "true",
                "create content": "member.type == \"editor\"",
                "update content": "member.type == \"editor\"",
                "delete content": "member.type == \"editor\""
            },
            "validations": [
                {
                    "expression": "content.data.headline != ''",
                    "message": "Bitte geben Sie eine \u00dcberschrift ein.",
                    "path": "headline",
                    "groups": [
                        "CREATE",
                        "UPDATE"
                    ]
                }
            ],
            "locales": "@locales"
        }
    ]
}
</pre>

**Comment by franzwilding** [comment]
Hm. I just added the two domains in unitecms.io, created an API key, added the key to both domains as "viewer" and everything is working just fine. 

Can you update to 0.8.2 (which does not include any breaking changes) and see if the problem is still there?

**Comment by MelanieJakob** [comment]
I have updated to 0.8.2 and now it works. Thank you.

**Comment by franzwilding** [comment]
Good to hear :)
