### ISSUE TITLE
Make storage bundle compatible to Exoscale Buckets

### ISSUE THREAD

**Issue by stefan-kamsker** [unite-cms/unite-cms#677]
Exoscale object storage needs the acl option to grant read permission to uploaded files

`'acl' => 'public-read'`

permissions aren't inherited
this option currently seems only to work on AWS, with exoscale buckets, a JS error is thrown "t is not defined"

see also https://github.com/unite-cms/unite-cms/pull/570

**Comment by franzwilding** [comment]
Closed for the moment. Can be re-opened if it is not working with flysystem
