### ISSUE TITLE
Gedmo Error on default install

### ISSUE THREAD

**Issue by ReneKrewinkel** [unite-cms/unite-cms#679]
Installed a local version of unitecms (following the installation instructions), upon saving content (route: unitecms_core_content_create) an error occurs: 

`Uncaught PHP Exception Doctrine\Common\Persistence\Mapping\MappingException: "The class 'Gedmo\Loggable\Entity\LogEntry' was not found in the chain configured namespaces UniteCMS\CoreBundle\Entity" at unitecms/vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/Mapping/MappingException.php line 22`

**Comment by franzwilding** [comment]
Hey! Please see the doctrine config from version 0.9 and adjust your config to that: https://github.com/unite-cms/unite-cms/blob/master/config/packages/doctrine.yaml

**Comment by ReneKrewinkel** [comment]
@franzwilding Hi Franz, thanks for your help. I applied the config, but I still get the same error.

**Comment by franzwilding** [comment]
Hm. did you also clear your symfony cache and update the database schema (with doctrine)?

**Comment by ReneKrewinkel** [comment]
Yes, I even dropped the schema and started over

**Comment by franzwilding** [comment]
Hmm. What version of unite cms are you using? Just a fresh standard installation?

**Comment by ecordani** [comment]
Same error here with a fresh install, Unite version 0.8.

**Comment by franzwilding** [comment]
Hey @ecordani, I just checked the install guide and everthing should work if you follow this guide: https://www.unitecms.io/docs

```
composer create-project unite-cms/standard unitecms --stability dev
cd unitecms
bin/console doctrine:schema:update --force

# run the development server
bin/console serve:run
```

If the problem still occurs, please re-open this issue again!

**Comment by stiffroy** [comment]
This is still present. Please reopen the issue and try to figure out the real problem and its solution.
