### ISSUE TITLE
The class 'Gedmo\Loggable\Entity\LogEntry' was not found

### ISSUE THREAD

**Issue by ecordani** [unite-cms/unite-cms#694]
Hi!
I tried the default installation steps (PHP 7.2.18, MySql 5.7.24):
```
composer create-project unite-cms/standard unitecms --stability dev
cd unitecms
bin/console doctrine:schema:update --force

# run the development server
bin/console serve:run
```

When I try to create a new content I get the error:
**Uncaught PHP Exception Doctrine\Common\Persistence\Mapping\MappingException: "The class 'Gedmo\Loggable\Entity\LogEntry' was not found in the chain configured namespaces UniteCMS\CoreBundle\Entity"**
<img width="1312" alt="Schermata 2019-07-28 alle 20 39 10" src="https://user-images.githubusercontent.com/5382841/62011434-ac837900-b178-11e9-8790-8c723096242a.png">

**Comment by ecordani** [comment]
I tried also with the docker installation, same error.

**Comment by franzwilding** [comment]
Hey! What’s the exact version of unite cms core bundle, composer installed?

**Comment by ecordani** [comment]
Composer 1.8.6, unite-cms/core-bundle 0.8.2. Please, try also the docker install because the error is exactly the same I get on my Mac.
Thank you

**Comment by lutpy** [comment]
Any updates on this issue? I've got the same error on a fresh installation.

**Comment by stiffroy** [comment]
I think you have already resolved this problem but incase someone else is looking into it can check my answer at [issue 679](https://github.com/unite-cms/unite-cms/issues/679#issuecomment-518644734). May be it might help. But to mention here, _I am talking about a higher version_ of the application.

**Comment by ecordani** [comment]
> I think you have already resolved this problem but incase someone else is looking into it can check my answer at [issue 679](https://github.com/unite-cms/unite-cms/issues/679#issuecomment-518644734). May be it might help. But to mention here, _I am talking about a higher version_ of the application.

Thank you very much!

**Comment by eltomato89** [comment]
I still have trouble with this one! Got a fresh git checkout and have setup the cms using the docs (using composer).
Seems like there is still something wrong. (I have the current doctrine.yaml deployed with `auto_mapping: true`)

Haven't deep dived doctrine internals but the exception is thrown in "vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/LoggableListener.php" (Line 278) `$logEntryMeta = $om->getClassMetadata($logEntryClass);`

Problem here could be related to "/vendor/unite-cms/core-bundle/Entity/Content.php" entity. Removing the `@Gedmo\Loggable` and `@Gedmo\Versioned` declarations, it works out fine ..

Maybe missing some meta?
