### ISSUE TITLE
Symfony asking for environment file even if system-wide environment variable APP_ENV=prod properly setup

### ISSUE THREAD

**Issue by massivedynamics1** [unite-cms/unite-cms#695]
$ lsb_release -a
Description:    Ubuntu 18.04.2 LTS
$ php -v
PHP 7.3.7-2+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jul 25 2019 11:44:40) ( NTS )

unite-cms installed without errors.

/etc/environment
```
ROUTING_APPROACH=parameter`
DEFAULT_HOSTNAME=
DATABASE_NAME=unite
DATABASE_USER=unite-admin
DATABASE_PASSWORD=
DATABASE_HOST=
DATABASE_PORT=3306
APP_ENV=prod
APP_SECRET=SECRET
MAILER_SENDER=test@example.com
MAILER_URL=smtp://127.0.0.1:1025
```

```
:~$ printenv APP_ENV
prod
~$ printenv APP_SECRET
SECRET

```
/var/log/nginx/project_error.log
Stack trace:
```
Stack trace:
#0 /var/www/unite/vendor/symfony/symfony/src/Symfony/Component/Dotenv/Dotenv.php(65): Symfony\Comp$
#1 /var/www/unite/public/index.php(18): Symfony\Component\Dotenv\Dotenv->load('/var/www/unite/...')
#2 {main}
  thrown in /var/www/unite/vendor/symfony/symfony/src/Symfony/Component/Dotenv/Dotenv.php on line $

```

Error when I try to load the webpage:
` Fatal error: Uncaught Symfony\Component\Dotenv\Exception\PathException: Unable to read the "/var/www/unite/public/../.env" environment file. in /var/www/unite/vendor/symfony/symfony/src/Symfony/Component/Dotenv/Dotenv.php:484 Stack trace: #0 /var/www/unite/vendor/symfony/symfony/src/Symfony/Component/Dotenv/Dotenv.php(65): Symfony\Component\Dotenv\Dotenv->doLoad(false, Array) #1 /var/www/unite/public/index.php(18): Symfony\Component\Dotenv\Dotenv->load('/var/www/unite/...') #2 {main} thrown in /var/www/unite/vendor/symfony/symfony/src/Symfony/Component/Dotenv/Dotenv.php on line 484`

/etc/nginx/sites-available/unite
```
server {
    listen 80;
    listen [::]:80;

    server_name ;
    root /var/www/unite/public;
    index index.php;
    client_max_body_size 100m;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php {
        try_files $uri /index.php =404;
        fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_index index.php;
        include fastcgi_params;
      }

    location ~ /\.(?:ht|git|svn) {
        deny all;
    }
   error_log /var/log/nginx/project_error.log;
   access_log /var/log/nginx/project_access.log;
}
```
Anyone?

**Comment by alanpilloud** [comment]
Same problem here. I now have an empty .env file just to avoid this issue.

**Comment by dynamiccontent** [comment]
To fix this problem you need to add fastcgi_param for all environment variables to your /etc/nginx/sites-available/unite

example of working config

server {
    server_name example.com www.example.com;
    root /var/www/unite/public;
    location / {
        # try to serve file directly, fallback to index.php
        try_files $uri /index.php$is_args$args;
}
    location ~ ^/index\.php(/|$) {
        fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param APP_DEBUG "1";
        fastcgi_param APP_ENV "prod";
        fastcgi_param DEFAULT_HOSTNAME "example.com";
        fastcgi_param APP_SECRET "SECRET";
        fastcgi_param ROUTING_APPROACH "parameter";
        fastcgi_param DATABASE_HOST "127.0.0.1";
        fastcgi_param DATABASE_PORT "3306";
        fastcgi_param DATABASE_NAME "unite";
        fastcgi_param DATABASE_USER "unite";
        fastcgi_param DATABASE_PASSWORD "password";
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        internal;
}
    location ~ \.php$ {
        return 404;
}
    error_log /var/log/nginx/project_error.log;
    access_log /var/log/nginx/project_access.log;
}
