### ISSUE TITLE
Video on website has no audio?

### ISSUE THREAD

**Issue by supersexy** [unite-cms/unite-cms#699]
This is awkward: you put a video on the most important place of your website, but that video has **no audio** - why? This is such a missed opportunity!

You should put some audio there to **explain things** - there are many things visible in that video that might be better understood when somebody would explain them, e.g. there is the word "domain" - it is not clear what this means in the context of your software - is it a DNS domain name? Or is this a key word taken from an advanced software development concept that a "generic user" would never understand? Also: how did you get to that screen in that video?  

BTW also please always **mind the viewers limited life time** and keep a video as short as possible, compact the knowledge and avoid time wasters - it is very annoying to watch a person typing slowly if that code could be presented in a text file. It still makes sense to show code in videos, but only if a voice explains the concept. 

One more: a video without audio **always** should contain some notice about that fact, like e.g. "This video has no audio, your speakers are most certainly not broken." or similar.

**Comment by franzwilding** [comment]
You are right. However because of the big changes of 0.10, we will do a refactoring of the website eventuelly, so the Video will be replaced or removed
