### ISSUE TITLE
unite-cms vs api-platform?

### ISSUE THREAD

**Issue by supersexy** [unite-cms/unite-cms#700]
Hi, this projects looks interesting, but I would like to understand:

What are the differences of this software compared to the standard [Symfony API bundle](https://api-platform.com)? 

It seems like you are building your own API-layer - please correct me if I am wrong.

Wouldn´t it be a much better strategy to build on top of api-platform and focus on building beautiful and easy to use CMS that could be installed with a Flex recipe? The api-platform is still very much a developer tool with rough edges - an easy to use cms-layer like unite-cms on top of that powerful platform would be a very good fit, also this would position your project right in the center of the Symfony community with much more attention! How do you like that?

**Comment by stiffroy** [comment]
I think the main difference would be in the storing of the data. Here in Unite CMS, one can create objects of any pattern but in the API Bundle all the Entity objects has to be created separately and are stored in their own respective tables. In Unite CMS, they use some generic structure to generate or store the data. These are all my assumptions but the core developers might be give more precise answer to your question or clear your doubt.

**Comment by franzwilding** [comment]
Hey @supersexy!

The idea behind unite cms is a CMS that allows you to define any kind of content structure without writing custom code / changing the database schema, exactly as @stiffroy described. 

In unite cms, the GraphQL API will be generated automatically based on the defined content structure.

**Comment by supersexy** [comment]
Ah, ok, so kind of a generic data store. Good to know. You should really emphasize that on the homepage. Good Luck!
