### ISSUE TITLE
Content Viewer

### ISSUE THREAD

**Issue by Benedict-Lojewski** [unite-cms/unite-cms#705]
In Gitter we discussed that it would be nice to have a role, where a user can see all contents but can't edit anything in the content. That would be a nice feature, if you work with other teams together, but don't want them to edit sensitive informations but only want them to see how the structure in the domain looks like with content.

What do you guys think about that feature?

**Comment by franzwilding** [comment]
This is possible with a custo mpermission: Only allow list/read (query)
