### ISSUE TITLE
Rendering Bug Edit Domain Firefox

### ISSUE THREAD

**Issue by stefan-kamsker** [unite-cms/unite-cms#71]
there is some sort of rendering bug in Firefox (tested with 59.0.3)

domain edit is cut off initially, if you open firebug it's gone

![2018-05-10 1](https://user-images.githubusercontent.com/34944934/39879576-7b53feb4-547b-11e8-9e27-16147a4e059c.png)
![2018-05-10](https://user-images.githubusercontent.com/34944934/39879577-7b7012d4-547b-11e8-88a9-065190478218.png)

**Comment by franzwilding** [comment]
I think this was fixed with https://github.com/unite-cms/unite-cms/commit/b9dffd109e1a2d1d91b7c690e602fe81d409da38. If this is still an issue @stefan-kamsker, please reopen.
