### ISSUE TITLE
Collection type in the Settings type content gives error

### ISSUE THREAD

**Issue by stiffroy** [unite-cms/unite-cms#710]
When creating a content in the `settings` type which has a field of `collection` type, then it gives an error:
```
Notice: Undefined index: {field_identifier}
```
But if this settings type content is created without the `collection` type and the edited and put back the `collection` type, then it works normally.

So to shorten up:
In the `settings` type:
Create new content type -> has `collection` type -> gives error
Updating existing content type -> adding a `collection` type -> works normally

**Comment by franzwilding** [comment]
There was a problem with sessting content before version 0.10: Until first save, there was no setting id but some of the fields internally needed an id. Should be fixed with version 0.10
