### ISSUE TITLE
"This form contains additional fields that are not allowed. Please reload this page."

### ISSUE THREAD

**Issue by alanpilloud** [unite-cms/unite-cms#724]
Hello,

After modifying the domain, when I try to edit a page, I have this error :+1: 

"This form contains additional fields that are not allowed. Please reload this page."

I understand that this is due to some removed field in the domain and that data still exists in the content.

At the moment, I just remove the content and re-create it, but this is not a real solution.

How could we manage this issue ?

**Comment by mafudelaptu** [comment]
same problem - push - +1

**Comment by franzwilding** [comment]
Hey! This problem can occur when changing the field config of collection fields  while content is present. A quick solution would be save the content somewhere, delete the collection rows hit save and add them again. 

In unite 0.10 we will try to find a better solution for content migration
