### ISSUE TITLE
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted ErrorHandler.php

### ISSUE THREAD

**Issue by dynamiccontent** [unite-cms/unite-cms#725]
PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted
(tried to allocate 20480 bytes) in
/home/user/unitecms/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php
 on line 620" while reading response header from upstream, client: IP,
server: webpage, request: "GET / HTTP/1.1", upstream:
"fastcgi://unix:/var/run/php/php7.1-fpm.sock:", host: "www.webpage"

I have tried everything. Changing PHP version and php parameters and always the same error.

Any advice?

**Comment by stefan-kamsker** [comment]
hi,

hard to say with no further logging

you could try a few things

set memory_limit to "-1" (unlimited) and check if it's working then or there's another error

check if your webserver is able to write to the following folders
config/unite
var/cache
var/log

BR

**Comment by dynamiccontent** [comment]
@stefan-kamsker 
Thank you pushing me in the right direction.
After adding writing permissions to folders the error changed to permission denied and I just had to do as explained below:
https://stackoverflow.com/questions/23443398/nginx-error-connect-to-php5-fpm-sock-failed-13-permission-denied#23487409
Thanks again!
