### ISSUE TITLE
Incompatible dependency

### ISSUE THREAD

**Issue by hedwiggggg** [unite-cms/unite-cms#727]
Trying to install I get the following error message.

<pre><font color="#4E9A06"><b>***@pop-os</b></font>:<font color="#3465A4"><b>~/Dokumente/github/unitecms</b></font>$ bin/console doctrine:schema:update --force

<font color="#C4A000">In MonologExtension.php line 55:</font>
<span style="background-color:#CC0000"><font color="#D3D7CF">                                                                                       </font></span>
<span style="background-color:#CC0000"><font color="#D3D7CF">  Symfony 5 is required for Monolog 2 support. Please downgrade Monolog to version 1.  </font></span>
<span style="background-color:#CC0000"><font color="#D3D7CF">                                                                                       </font></span>
</pre>

**Comment by franzwilding** [comment]
Hey!
Which version of unite cms are you using?

**Comment by dynamiccontent** [comment]
Have the same problem.
user@unitecms:~/unitecms$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.10
Release:        19.10
Codename:       eoan

user@unitecms:~/unitecms$ composer
Composer version 1.9.1 2019-11-01 17:20:17

user@unitecms:~/unitecms$ php -v
PHP 7.3.11-0ubuntu0.19.10.1 (cli) (built: Oct 24 2019 11:38:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11-0ubuntu0.19.10.1, Copyright (c) 1999-2018, by Zend Technologies


`user@unitecms:~$ composer create-project unite-cms/standard unitecms --stability dev --no-dev --no-scripts
Installing unite-cms/standard (dev-master 71819babbf0134e881edc65b60dbbcf445e1c96c)
  - Installing unite-cms/standard (dev-master 71819ba): Cloning 71819babbf from cache
Created project in unitecms
Loading composer repositories with package information
Updating dependencies
Package operations: 70 installs, 0 updates, 0 removals
  - Installing doctrine/lexer (1.2.0): Loading from cache
  - Installing doctrine/annotations (v1.8.0): Loading from cache
  - Installing doctrine/reflection (v1.0.0): Loading from cache
  - Installing doctrine/event-manager (1.1.0): Loading from cache
  - Installing doctrine/collections (v1.5.0): Loading from cache
  - Installing doctrine/cache (1.9.1): Downloading (100%)
  - Installing doctrine/persistence (1.2.0): Loading from cache
  - Installing doctrine/inflector (1.3.1): Loading from cache
  - Installing doctrine/common (v2.11.0): Loading from cache
  - Installing behat/transliterator (v1.2.0): Loading from cache
  - Installing gedmo/doctrine-extensions (v2.4.37): Loading from cache
  - Installing symfony/polyfill-php73 (v1.12.0): Loading from cache
  - Installing symfony/polyfill-php72 (v1.12.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.12.0): Loading from cache
  - Installing symfony/polyfill-intl-idn (v1.12.0): Loading from cache
  - Installing symfony/symfony (v4.3.8): Loading from cache
  - Installing symfony/polyfill-intl-icu (v1.12.0): Loading from cache
  - Installing symfony/polyfill-ctype (v1.12.0): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing symfony/contracts (v1.1.8): Loading from cache
  - Installing psr/log (1.1.2): Loading from cache
  - Installing psr/link (1.0.0): Loading from cache
  - Installing twig/twig (v2.12.2): Loading from cache
  - Installing fig/link-util (1.0.0): Loading from cache
  - Installing paragonie/random_compat (v9.99.99): Loading from cache
  - Installing stof/doctrine-extensions-bundle (v1.3.0): Loading from cache
  - Installing knplabs/knp-components (v1.3.10): Loading from cache
  - Installing knplabs/knp-paginator-bundle (v2.8.0): Loading from cache
  - Installing doctrine/doctrine-cache-bundle (1.3.5): Loading from cache
  - Installing jdorn/sql-formatter (v1.2.17): Loading from cache
  - Installing doctrine/dbal (v2.10.0): Loading from cache
  - Installing doctrine/doctrine-bundle (1.11.2): Loading from cache
  - Installing phpoption/phpoption (1.5.2): Loading from cache
  - Installing doctrine/instantiator (1.3.0): Loading from cache
  - Installing phpcollection/phpcollection (0.5.0): Loading from cache
  - Installing jms/parser-lib (1.0.0): Loading from cache
  - Installing jms/metadata (1.7.0): Loading from cache
  - Installing jms/serializer (1.14.0): Loading from cache
  - Installing jms/serializer-bundle (2.4.4): Loading from cache
  - Installing sensio/framework-extra-bundle (v5.5.1): Loading from cache
  - Installing monolog/monolog (2.0.1): Loading from cache
  - Installing symfony/monolog-bundle (v3.5.0): Loading from cache
  - Installing scienta/doctrine-json-functions (4.0.2): Loading from cache
  - Installing webonyx/graphql-php (v0.13.8): Loading from cache
  - Installing symfony/polyfill-iconv (v1.12.0): Loading from cache
  - Installing egulias/email-validator (2.1.11): Loading from cache
  - Installing swiftmailer/swiftmailer (v6.2.3): Loading from cache
  - Installing symfony/swiftmailer-bundle (v3.4.0): Loading from cache
  - Installing doctrine/orm (v2.6.4): Loading from cache
  - Installing oro/doctrine-extensions (1.3.0): Loading from cache
  - Installing cocur/slugify (v3.2): Loading from cache
  - Installing ralouphie/getallheaders (3.0.3): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.6.1): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing guzzlehttp/guzzle (6.4.1): Loading from cache
  - Installing unite-cms/core-bundle (v0.8.2): Loading from cache
  - Installing unite-cms/collection-field-bundle (v0.8.2): Loading from cache
  - Installing ramsey/uuid (3.8.0): Loading from cache
  - Installing mtdowling/jmespath.php (2.4.0): Loading from cache
  - Installing aws/aws-sdk-php (3.117.2): Downloading (100%)
  - Installing unite-cms/storage-bundle (v0.8.2): Loading from cache
  - Installing symfony/polyfill-intl-normalizer (v1.12.0): Loading from cache
  - Installing symfony/polyfill-intl-grapheme (v1.12.0): Loading from cache
  - Installing voku/portable-ascii (1.3.5): Loading from cache
  - Installing voku/portable-utf8 (5.4.27): Loading from cache
  - Installing voku/anti-xss (4.1.19): Loading from cache
  - Installing unite-cms/wysiwyg-field-bundle (v0.8.2): Loading from cache
  - Installing unite-cms/variants-field-bundle (v0.8.2): Loading from cache
Writing lock file
Generating autoload files
Do you want to remove the existing VCS (.git, .svn..) history? [Y,n]? y
user@unitecms:~$ cd unitecms/
user@unitecms:~/unitecms$ bin/console assets:install --env=prod

In MonologExtension.php line 55:

  Symfony 5 is required for Monolog 2 support. Please downgrade Monolog to ve
  rsion 1.
`

Some discussion about this problem:
- https://github.com/symfony/monolog-bundle/issues/330
- https://github.com/symfony/symfony/issues/34372
- https://github.com/ezsystems/ezplatform/pull/478

**Comment by rfnbnkr** [comment]
I have a same problem

**Comment by franzwilding** [comment]
Hey! The unite-cms/standard skeleton is not ready for the new 0.10-dev version, so please use version 0.9.x to install the latest stable version or if you want to try out 0.10-dev, please check out this repository!

in the next weeks, we will provide a new easy way to install 0.10, maybe by using flex instead of the unite-cms/standard skeleton
