### ISSUE TITLE
Argument 2 passed to UniteCMS\CoreBundle\Subscriber\CorsListener::__construct() must be an instance of Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage

### ISSUE THREAD

**Issue by dynamiccontent** [unite-cms/unite-cms#729]
Argument 2 passed to UniteCMS\CoreBundle\Subscriber\CorsListener::__construct() must be an instance of Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage, instance of Symfony\Component\Security\Core\Authentication\Token\Storage\UsageTrackingTokenStorage given, called in /var/www/unitecms/var/cache/prod/ContainerZnSN1Z6/srcApp_KernelProdDebugContainer.php on line 927
https://imgur.com/a/HOVoSks (image of the error)

Installing for production via https://www.unitecms.io/docs.html successfully.
Added permissions read/write for webserver to var/cache, var/log and unitecms/unitecms

Maybe I am installing this the wrong way? @franzwilding advised to install 0.9.x to install the latest stable version here https://github.com/unite-cms/unite-cms/issues/727 but I can't seem to find the way to do that.

Any advice?

**Comment by lexermal** [comment]
Hello, 
I got the same issue. I used the command shown in the Lobby to get 0.9.1 installed, but the error still occurred. 

Recreation via running these commands:
` 
composer create-project unite-cms/standard:0.9.1 unitecms --stability dev
ch unitecms
bin/console doctrine:schema:update --force
bin/console unite:user:create
bin/console unite:organization:create
bin/console serve:run
`

Any idea?

**Comment by franzwilding** [comment]
Hey! You can now test out the first preview of 0.10-dev (https://github.com/unite-cms/unite-cms/issues/730) if you just want to test it out. 

If you want to use 0.9.1 for a real project, please try to use this "require" section in composer.json and run composer update again: 

```
"require": {
        "symfony/symfony": "4.3",
        "monolog/monolog": "^1.25",
        "unite-cms/core-bundle": "^0.9",
        "unite-cms/collection-field-bundle": "^0.9",
        "unite-cms/storage-bundle": "^0.9",
        "unite-cms/wysiwyg-field-bundle": "^0.9",
        "unite-cms/variants-field-bundle": "^0.9"
    },```
