### ISSUE TITLE
Short install guide: unite cms 0.10-DEV

### ISSUE THREAD

**Issue by franzwilding** [unite-cms/unite-cms#730]
Hey!

At the moment we are working hard on the next version of unite cms: v0.10. Since this is a very big change, we also need to refactor our docs to reflect the new codebase. 

Until we are finishing this (we are planning to have the first version until the end of this year), you can play around with the new code using the following mini install guide: 

```bash
git clone git@github.com:unite-cms/unite-cms.git
cd unite-cms

# Set database env var
add DATABASE_URL env variable to .env (e.g. DATABASE_URL=mysql://user:password@127.0.0.1:3306/unite_cms)

composer install
bin/console doctrine:schema:update --em=default --force

# Create JWT keys (see https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md#installation)
mkdir -p config/jwt
openssl genpkey -out config/jwt/private.pem -aes256 -algorithm rsa -pkeyopt rsa_keygen_bits:4096
openssl pkey -in config/jwt/private.pem -out config/jwt/public.pem -pubout

# Set JWT passphrase env var
add JWT_PASSPHRASE to .env

# Install assets
yarn install
yarn build

# Create first admin user
bin/console unite:user:create Admin admin@example.com password --persist

# Run server
bin/console server:run
```

Now you can edit update ./config/unite/default/*.graphql to set your content types, admin interfaces etc.

Have fun and post your feedback!

**Comment by ehibes** [comment]
Hi, 

I have the following error when I make admin creation command : 
` embeddedContentTypes[SEO].fields: Invalid GraphQL return type "UniteContentMeta" for
  field of type "text". Please use on of [String].
`

**Comment by franzwilding** [comment]
Hey! You have an error in your graphql schema. you need to do something like this: 

type SEO implements UniteContent {
    _meta: UniteContentMeta!
    id: ID
    text: String @textField
}

text field must be of type String

**Comment by franzwilding** [comment]
Install guide was added to docs: https://docs.unitecms.io/docs/
