### ISSUE TITLE
  contentTypes[articles].views[all].settings: The child node "columns" at path "settings" is deprecated.

### ISSUE THREAD

**Issue by dynamiccontent** [unite-cms/unite-cms#732]
Hello,
Been trying to setup https://medium.com/unite-cms/create-a-blog-using-unite-cms-vue-js-2784743bb488 so I can understand better how your project works but I keep getting this error

contentTypes[articles].views[all].settings: The child node "columns" at path "settings" is deprecated.

I am running unite cms 0.9.1.
Should I downgrade to unite cms v0.8.0 so I can try this example?

**Comment by franzwilding** [comment]
Please see my answer on your question on the other issue!
