### ISSUE TITLE
Setup on shared hosting

### ISSUE THREAD

**Issue by lexermal** [unite-cms/unite-cms#759]
Hello everyone,

I'm trying to setup unite on an shared hosting environment. Until now I was able to see the login screen, but the page is not loading the assets and the login does not work. I tried with a local lampp setup and on my shared hosting provider on the path localhost/projectX/unite. 
The unite 0.10 did also not work, it threw an exception.

How can I set it up with relative paths without the build in webserver(my shared hosting provides does not provide shell access)?

Thanks in advance!

The following is how I came to the above result.

## My Setup for shared hosting
1. composer create-project unite-cms/standard:0.9.1 unitecms --stability dev --no-dev --no-scripts
2. cd unitecms
3. Change the composer.json file and set the following in require: 
 ~~~~
"symfony/symfony": "4.3",
"monolog/monolog": "^1.25",
"unite-cms/core-bundle": "^0.9",
"unite-cms/collection-field-bundle": "^0.9",
"unite-cms/storage-bundle": "^0.9",
"unite-cms/wysiwyg-field-bundle": "^0.9",
"unite-cms/variants-field-bundle": "^0.9"
~~~~
4. composer update
5. composer install
6. bin/console assets:install --env=prod
7. bin/console doctrine:schema:update --force --env=prod
8. bin/console cache:clear --env=prod
9. bin/console unite:user:create
10. bin/console unite:organization:create
11. Create a .htaccess file in /public with the following content:
```
<IfModule mod_rewrite.c>
    Options -MultiViews
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ index.php [QSA,L]
</IfModule>

<IfModule !mod_rewrite.c>
    <IfModule mod_alias.c>
        RedirectMatch 302 ^/$ /index.php/
    </IfModule>
</IfModule>
```
12. Edit the .env file with the following content:
```
APP_ENV=prod
ROUTING_APPROACH=parameter
DEFAULT_HOSTNAME=localhost
APP_SECRET=SECRET
DATABASE_HOST=localhost
DATABASE_PORT=3306
DATABASE_NAME=xxx
DATABASE_USER=xxx
DATABASE_PASSWORD=xxx
MAILER_SENDER=test@example.com
MAILER_URL=smtp://127.0.0.1:1025
```
Filled in the database information of the shared hosting provider.
13. Transfair the database and files to the shared hosting provider.

**Comment by svirmi** [comment]
Hi! Are you able to install clean Symfony framework there?

**Comment by lexermal** [comment]
Yes, via Plugin system(Softaculous), but I have no terminal.
